/* ================================================================
   AGENTS DATA — AIOS + Xquads
   ================================================================ */

const SQUADS_META = {
  'aiox': {
    name: 'AIOX', color: '#7cd3ff', icon: '🤖',
    desc: 'Framework de desenvolvimento ágil',
    notable: 'Dev, QA, Architect, DevOps, PM, PO, SM...',
    xquad: false,
  },
  'advisory-board': {
    name: 'Advisory Board', color: '#a78bfa', icon: '🏛️',
    desc: 'Conselheiros estratégicos',
    notable: 'Ray Dalio, Charlie Munger, Naval Ravikant...',
    xquad: true,
  },
  'brand-squad': {
    name: 'Brand Squad', color: '#f472b6', icon: '🎨',
    desc: 'Branding e posicionamento',
    notable: 'David Aaker, Marty Neumeier, Al Ries...',
    xquad: true,
  },
  'c-level-squad': {
    name: 'C-Level Squad', color: '#fbbf24', icon: '👔',
    desc: 'Liderança executiva',
    notable: 'CEO, CTO, CMO, COO, CIO, CAIO',
    xquad: true,
  },
  'claude-code-mastery': {
    name: 'Claude Code Mastery', color: '#22d3ee', icon: '⚡',
    desc: 'Domínio do Claude Code e AIOS',
    notable: 'Config, Hooks, MCP, Swarm, Skills...',
    xquad: true,
  },
  'copy-master': {
    name: 'Copy Master', color: '#fb923c', icon: '✍️',
    desc: 'Copywriting — os maiores da história',
    notable: 'Gary Halbert, Eugene Schwartz, David Ogilvy...',
    xquad: true,
  },
  'cybersecurity': {
    name: 'Cybersecurity', color: '#f87171', icon: '🛡️',
    desc: 'Segurança ofensiva e defensiva',
    notable: 'Recon, Fuzzer, OSINT, Red Team, AppSec...',
    xquad: true,
  },
  'data-squad': {
    name: 'Data Squad', color: '#60a5fa', icon: '📊',
    desc: 'Analytics, growth e comunidade',
    notable: 'Sean Ellis, Avinash Kaushik, Peter Fader...',
    xquad: true,
  },
  'design-squad': {
    name: 'Design Squad', color: '#c084fc', icon: '🖌️',
    desc: 'UX/UI e design systems',
    notable: 'Brad Frost, Dan Mall, Dave Malouf...',
    xquad: true,
  },
  'hormozi-squad': {
    name: 'Hormozi Squad', color: '#f59e0b', icon: '💰',
    desc: 'Negócios e escala',
    notable: 'Offers, Leads, Pricing, Scale, Closer...',
    xquad: true,
  },
  'movement': {
    name: 'Movement', color: '#34d399', icon: '✊',
    desc: 'Construção de movimentos e comunidades',
    notable: 'Architect, Manifesto, Identidade, Impacto...',
    xquad: true,
  },
  'storytelling': {
    name: 'Storytelling', color: '#818cf8', icon: '📖',
    desc: 'Narrativa e storytelling',
    notable: 'Joseph Campbell, Oren Klaff, Nancy Duarte...',
    xquad: true,
  },
  'traffic-masters': {
    name: 'Traffic Masters', color: '#f97316', icon: '📣',
    desc: 'Tráfego pago e mídia',
    notable: 'Pedro Sobral, Kasim Aslam, Molly Pittman...',
    xquad: true,
  },
};

const FUNCTIONS_META = {
  tech:      { name: 'Tecnologia',   icon: '💻', color: '#7cd3ff' },
  strategy:  { name: 'Estratégia',   icon: '♟️', color: '#a78bfa' },
  marketing: { name: 'Marketing',    icon: '📣', color: '#f97316' },
  copy:      { name: 'Copy',         icon: '✍️', color: '#fb923c' },
  brand:     { name: 'Branding',     icon: '🎨', color: '#f472b6' },
  security:  { name: 'Segurança',    icon: '🛡️', color: '#f87171' },
  data:      { name: 'Dados',        icon: '📊', color: '#60a5fa' },
  movement:  { name: 'Comunidade',   icon: '🌱', color: '#34d399' },
  story:     { name: 'Narrativa',    icon: '📖', color: '#818cf8' },
  business:  { name: 'Negócios',     icon: '💼', color: '#fbbf24' },
};
const FUNCTIONS_ORDER = ['tech','strategy','marketing','copy','brand','security','data','movement','story','business'];

const AGENTS_DB = [

  /* ── AIOX ─────────────────────────────────────────────────────── */
  { id:'aiox-orion',   name:'Orion',  icon:'👑', squad:'aiox', fn:'tech',
    title:'AIOX Master Orchestrator', tagline:'Expertise total + orquestração de workflows',
    command:'/AIOX:agents:aiox-master',
    when:'Para expertise abrangente em múltiplos domínios, criação de componentes do framework ou tarefas sem persona especializada.' },
  { id:'aiox-atlas',   name:'Atlas',  icon:'🔍', squad:'aiox', fn:'tech',
    title:'Business Analyst', tagline:'Análise de negócios e requisitos',
    command:'/AIOX:agents:analyst',
    when:'Análise de requisitos, documentação de processos, elicitação de stakeholders e modelagem de negócios.' },
  { id:'aiox-aria',    name:'Aria',   icon:'🏛️', squad:'aiox', fn:'tech',
    title:'Architect', tagline:'Arquitetura de software e decisões técnicas',
    command:'/AIOX:agents:architect',
    when:'Decisões de arquitetura, design de sistemas, avaliação de trade-offs técnicos e revisão de stack.' },
  { id:'aiox-dara',    name:'Dara',   icon:'📊', squad:'aiox', fn:'tech',
    title:'Database Architect', tagline:'Banco de dados, Supabase e RLS',
    command:'/AIOX:agents:data-engineer',
    when:'Design de schema, policies RLS, migrations, otimização de queries e modelagem de dados.' },
  { id:'aiox-dex',     name:'Dex',    icon:'💻', squad:'aiox', fn:'tech',
    title:'Full Stack Developer', tagline:'Implementação, debug e refatoração',
    command:'/AIOX:agents:dev',
    when:'Implementação de código, debugging, refatoração e boas práticas de desenvolvimento.' },
  { id:'aiox-gage',    name:'Gage',   icon:'⚡', squad:'aiox', fn:'tech',
    title:'DevOps Specialist', tagline:'GitHub, CI/CD e push para remoto',
    command:'/AIOX:agents:devops',
    when:'Operações de repositório, versionamento, CI/CD, quality gates e push para GitHub. Único agente autorizado a fazer push.' },
  { id:'aiox-morgan',  name:'Morgan', icon:'📋', squad:'aiox', fn:'strategy',
    title:'Product Manager', tagline:'Produto, roadmap e descoberta',
    command:'/AIOX:agents:pm',
    when:'Definição de roadmap, descoberta de produto, alinhamento de stakeholders e estratégia de features.' },
  { id:'aiox-pax',     name:'Pax',    icon:'🎯', squad:'aiox', fn:'strategy',
    title:'Product Owner', tagline:'Backlog, stories e critérios de aceitação',
    command:'/AIOX:agents:po',
    when:'Gestão de backlog, refinamento de stories, critérios de aceitação e planejamento de sprint.' },
  { id:'aiox-quinn',   name:'Quinn',  icon:'✅', squad:'aiox', fn:'tech',
    title:'Test Architect', tagline:'Qualidade, testes e revisão de código',
    command:'/AIOX:agents:qa',
    when:'Arquitetura de testes, revisão de qualidade, rastreabilidade de requisitos e estratégia de QA.' },
  { id:'aiox-river',   name:'River',  icon:'🌊', squad:'aiox', fn:'strategy',
    title:'Scrum Master', tagline:'Cerimônias ágeis e remoção de impedimentos',
    command:'/AIOX:agents:sm',
    when:'Facilitação de cerimônias Scrum, remoção de impedimentos e coaching de times ágeis.' },
  { id:'aiox-craft',   name:'Craft',  icon:'🏗️', squad:'aiox', fn:'tech',
    title:'Squad Creator', tagline:'Criar, validar e publicar squads',
    command:'/AIOX:agents:squad-creator',
    when:'Criar, validar, publicar e gerenciar squads de agentes.' },
  { id:'aiox-uma',     name:'Uma',    icon:'🎨', squad:'aiox', fn:'tech',
    title:'UX/UI Designer', tagline:'Research, wireframes e design systems',
    command:'/AIOX:agents:ux-design-expert',
    when:'Workflow completo de design: pesquisa, wireframes, design systems, extração de tokens e QA.' },

  /* ── ADVISORY BOARD ─────────────────────────────────────────── */
  { id:'ab-chair',    name:'Board Chair',     icon:'🏛️', squad:'advisory-board', fn:'strategy',
    title:'Advisory Board Orchestrator', tagline:'Facilitação estratégica e síntese de sabedoria',
    command:'/advisory-board:agents:board-chair',
    when:'Quando precisar de conselho estratégico multidisciplinar ou convocar múltiplos conselheiros.' },
  { id:'ab-brene',    name:'Brené Brown',     icon:'💛', squad:'advisory-board', fn:'strategy',
    title:'Vulnerability & Courageous Leadership', tagline:'Coragem, vergonha e segurança psicológica',
    command:'/advisory-board:agents:brene-brown',
    when:'Construir confiança em times, desenvolver liderança corajosa ou criar cultura de pertencimento.' },
  { id:'ab-munger',   name:'Charlie Munger',  icon:'🧠', squad:'advisory-board', fn:'strategy',
    title:'Multidisciplinary Thinker', tagline:'Mental models, vieses cognitivos e pensamento racional',
    command:'/advisory-board:agents:charlie-munger',
    when:'Problemas que exigem múltiplos mental models, vieses cognitivos ou avaliação de vantagens competitivas.' },
  { id:'ab-sivers',   name:'Derek Sivers',    icon:'🎯', squad:'advisory-board', fn:'strategy',
    title:'Minimalist Founder', tagline:'Hell Yeah or No — simplicidade e anti-escala',
    command:'/advisory-board:agents:derek-sivers',
    when:'Decidir sobre oportunidades, simplificar decisões ou resistir à pressão de escalar.' },
  { id:'ab-naval',    name:'Naval Ravikant',  icon:'🧘', squad:'advisory-board', fn:'strategy',
    title:'Philosopher-Investor', tagline:'Riqueza, leverage e felicidade',
    command:'/advisory-board:agents:naval-ravikant',
    when:'Clareza sobre criação de riqueza, leverage, specific knowledge ou frameworks de felicidade.' },
  { id:'ab-lencioni', name:'Patrick Lencioni',icon:'🏗️', squad:'advisory-board', fn:'strategy',
    title:'Master of Team Dynamics', tagline:'Disfunções de time e saúde organizacional',
    command:'/advisory-board:agents:patrick-lencioni',
    when:'Times disfuncionais, reuniões improdutivas, problemas de accountability ou cultura organizacional.' },
  { id:'ab-thiel',    name:'Peter Thiel',     icon:'♟️', squad:'advisory-board', fn:'strategy',
    title:'Contrarian Venture Philosopher', tagline:'Monopólio, zero-to-one e segredos',
    command:'/advisory-board:agents:peter-thiel',
    when:'Análise contrarian, avaliar se um negócio cria valor de monopólio real ou apenas compete.' },
  { id:'ab-dalio',    name:'Ray Dalio',       icon:'📐', squad:'advisory-board', fn:'strategy',
    title:'Principles Architect', tagline:'Decisões sistemáticas, ciclos econômicos e radical truth',
    command:'/advisory-board:agents:ray-dalio',
    when:'Framework sistemático para decisões, diagnóstico de causa raiz ou cultura de transparência radical.' },
  { id:'ab-reid',     name:'Reid Hoffman',    icon:'🔗', squad:'advisory-board', fn:'strategy',
    title:'Oracle of Networks', tagline:'Blitzscaling e efeitos de rede',
    command:'/advisory-board:agents:reid-hoffman',
    when:'Estratégia de escala, análise de efeitos de rede, planejamento ABZ ou blitzscaling.' },
  { id:'ab-sinek',    name:'Simon Sinek',     icon:'⭕', squad:'advisory-board', fn:'strategy',
    title:'Purpose-Driven Leadership', tagline:'Start With Why e mentalidade infinita',
    command:'/advisory-board:agents:simon-sinek',
    when:'Organização sem propósito claro, líderes que precisam inspirar ou transição para mentalidade infinita.' },
  { id:'ab-yvon',     name:'Yvon Chouinard',  icon:'🏔️', squad:'advisory-board', fn:'strategy',
    title:'Reluctant Businessman', tagline:'Propósito, planeta e anti-crescimento',
    command:'/advisory-board:agents:yvon-chouinard',
    when:'Questionar crescimento a qualquer custo ou construir empresa orientada por missão.' },

  /* ── BRAND SQUAD ─────────────────────────────────────────────── */
  { id:'brand-chief',   name:'Brand Chief',       icon:'🎨', squad:'brand-squad', fn:'brand',
    title:'Brand Squad Orchestrator', tagline:'Roteamento estratégico de brand',
    command:'/brand-squad:agents:brand-chief',
    when:'Qualquer desafio de marca que precise ser roteado para o especialista certo.' },
  { id:'brand-al',      name:'Al Ries',            icon:'🏔️', squad:'brand-squad', fn:'brand',
    title:'Father of Positioning', tagline:'Leis do marketing e estratégia de categoria',
    command:'/brand-squad:agents:al-ries',
    when:'Posicionamento ou reposicionamento de marca, criação de categorias ou foco e sacrifício estratégico.' },
  { id:'brand-alina',   name:'Alina Wheeler',      icon:'✏️', squad:'brand-squad', fn:'brand',
    title:'Brand Identity Authority', tagline:'Processo de 5 fases e design de identidade',
    command:'/brand-squad:agents:alina-wheeler',
    when:'Projetar sistema completo de identidade visual ou avaliar identidade contra os 9 ideais.' },
  { id:'brand-arch',    name:'Archetype Consultant',icon:'🎭', squad:'brand-squad', fn:'brand',
    title:'Brand Personality Architect', tagline:'Arquétipos jungianos e tom de voz',
    command:'/brand-squad:agents:archetype-consultant',
    when:'Definir personalidade de marca, mapear arquétipos ou criar diretrizes de tom de voz.' },
  { id:'brand-byron',   name:'Byron Sharp',        icon:'🔬', squad:'brand-squad', fn:'brand',
    title:'Marketing Scientist', tagline:'Brand growth baseado em evidências',
    command:'/brand-squad:agents:byron-sharp',
    when:'Desafiar suposições de marketing com evidências ou planejar estratégia de mídia para crescimento.' },
  { id:'brand-aaker',   name:'David Aaker',        icon:'👑', squad:'brand-squad', fn:'brand',
    title:'Father of Modern Branding', tagline:'Brand equity, identidade e arquitetura',
    command:'/brand-squad:agents:david-aaker',
    when:'Construir ou medir brand equity, definir identidade de marca ou decisões de arquitetura de marca.' },
  { id:'brand-denise',  name:'Denise Yohn',        icon:'🔗', squad:'brand-squad', fn:'brand',
    title:'Brand-Culture Fusion Expert', tagline:'Marca e cultura alinhadas de dentro para fora',
    command:'/brand-squad:agents:denise-yohn',
    when:'Marca e cultura desalinhadas ou fortalecer o branding interno.' },
  { id:'brand-domain',  name:'Domain Scout',       icon:'🔎', squad:'brand-squad', fn:'brand',
    title:'Digital Naming Specialist', tagline:'Domínios e handles para sua marca',
    command:'/brand-squad:agents:domain-scout',
    when:'Verificar disponibilidade de domínios para nomes de marca ou estratégia de handles sociais.' },
  { id:'brand-miller',  name:'Donald Miller',      icon:'📖', squad:'brand-squad', fn:'brand',
    title:'StoryBrand Creator', tagline:'SB7 Framework e mensagem clarificada',
    command:'/brand-squad:agents:donald-miller',
    when:'Mensagem de marca confusa, criar BrandScript ou aplicar estrutura de história ao marketing.' },
  { id:'brand-emily',   name:'Emily Heyward',      icon:'🚀', squad:'brand-squad', fn:'brand',
    title:'Startup Brand Architect', tagline:'Marcas DTC e lançamento de startups',
    command:'/brand-squad:agents:emily-heyward',
    when:'Lançar uma nova marca do zero ou construir marcas DTC/startup.' },
  { id:'brand-kapferer',name:'Jean-Noël Kapferer', icon:'💠', squad:'brand-squad', fn:'brand',
    title:'Brand Identity Prism Creator', tagline:'Prisma de identidade e gestão de luxo',
    command:'/brand-squad:agents:jean-noel-kapferer',
    when:'Definir identidade de marca (não só visual) ou gerenciar marcas de luxo.' },
  { id:'brand-keller',  name:'Kevin Lane Keller',  icon:'📐', squad:'brand-squad', fn:'brand',
    title:'CBBE Pyramid Creator', tagline:'Medição de brand equity e posicionamento',
    command:'/brand-squad:agents:kevin-keller',
    when:'Medir brand equity, construir a pirâmide CBBE ou definir posicionamento com POPs e PODs.' },
  { id:'brand-marty',   name:'Marty Neumeier',     icon:'⚡', squad:'brand-squad', fn:'brand',
    title:'Brand Gap Pioneer', tagline:'Diferenciação radical e a declaração de onlyness',
    command:'/brand-squad:agents:marty-neumeier',
    when:'Diferenciação radical ou quando a marca parece genérica — construir o enunciado de onlyness.' },
  { id:'brand-sticky',  name:'Miller Sticky Brand', icon:'📋', squad:'brand-squad', fn:'brand',
    title:'StoryBrand Implementation Engine', tagline:'BrandScript ao funil — execução',
    command:'/brand-squad:agents:miller-sticky-brand',
    when:'Implementar StoryBrand na prática: BrandScripts, one-liners, sites wireframe e sequências de email.' },
  { id:'brand-naming',  name:'Naming Strategist',  icon:'💎', squad:'brand-squad', fn:'brand',
    title:'Brand Naming Specialist', tagline:'Arquitetura linguística e estratégica de nomes',
    command:'/brand-squad:agents:naming-strategist',
    when:'Criar um novo nome de marca, avaliar nomes existentes ou checar viabilidade linguística.' },

  /* ── C-LEVEL SQUAD ───────────────────────────────────────────── */
  { id:'cl-caio',   name:'CAIO Architect',   icon:'🤖', squad:'c-level-squad', fn:'strategy',
    title:'AI Strategy Specialist', tagline:'Estratégia de IA e arquitetura de sistemas inteligentes',
    command:'/c-level-squad:agents:caio-architect',
    when:'Estratégia de IA, design de pipeline ML, governança de IA responsável ou integração de LLMs.' },
  { id:'cl-cio',    name:'CIO Engineer',     icon:'🖥️', squad:'c-level-squad', fn:'strategy',
    title:'Information Systems Specialist', tagline:'Arquitetura enterprise, segurança e compliance',
    command:'/c-level-squad:agents:cio-engineer',
    when:'Desafios de sistemas de informação, compliance (SOC2, GDPR, HIPAA) ou transformação digital.' },
  { id:'cl-cmo',    name:'CMO Architect',    icon:'📣', squad:'c-level-squad', fn:'marketing',
    title:'Marketing Strategy Specialist', tagline:'Posicionamento, GTM e aquisição de clientes',
    command:'/c-level-squad:agents:cmo-architect',
    when:'Posicionamento de marca, estratégia go-to-market ou quando o marketing parece aleatório.' },
  { id:'cl-coo',    name:'COO Orchestrator', icon:'⚙️', squad:'c-level-squad', fn:'business',
    title:'Operational Excellence Specialist', tagline:'Escalar operações sem quebrar',
    command:'/c-level-squad:agents:coo-orchestrator',
    when:'Gargalos de escalabilidade, processos quebrados, estrutura de time ou design de KPIs.' },
  { id:'cl-cto',    name:'CTO Architect',    icon:'🔧', squad:'c-level-squad', fn:'tech',
    title:'Technology Strategy Specialist', tagline:'Estratégia tech e liderança de engenharia',
    command:'/c-level-squad:agents:cto-architect',
    when:'Decisões de arquitetura, build vs buy, dívida técnica ou estrutura do time de engenharia.' },
  { id:'cl-vision', name:'Vision Chief',     icon:'👔', squad:'c-level-squad', fn:'strategy',
    title:'Strategic Vision Orchestrator', tagline:'Conselho de CEO e visão executiva holística',
    command:'/c-level-squad:agents:vision-chief',
    when:'Conselho de nível CEO, visão da empresa, fundraising, cultura ou decisões existenciais.' },

  /* ── CLAUDE CODE MASTERY ─────────────────────────────────────── */
  { id:'ccm-orion',  name:'Orion',   icon:'🧠', squad:'claude-code-mastery', fn:'tech',
    title:'Claude Code Mastery Orchestrator', tagline:'Maestro do Claude Code',
    command:'/claude-code-mastery:agents:claude-mastery-chief',
    when:'Orquestrar domínio completo do Claude Code ou rotear tarefas para o especialista certo do squad.' },
  { id:'ccm-sigil',  name:'Sigil',   icon:'⚙️', squad:'claude-code-mastery', fn:'tech',
    title:'Configuration Engineer', tagline:'settings.json, permissões e variáveis',
    command:'/claude-code-mastery:agents:config-engineer',
    when:'Configurar Claude Code via settings.json, permissões, hooks ou variáveis de ambiente.' },
  { id:'ccm-latch',  name:'Latch',   icon:'🎣', squad:'claude-code-mastery', fn:'tech',
    title:'Hooks Architect', tagline:'Hooks de automação no Claude Code',
    command:'/claude-code-mastery:agents:hooks-architect',
    when:'Projetar e implementar hooks de automação para o ciclo de vida do Claude Code.' },
  { id:'ccm-piper',  name:'Piper',   icon:'🔌', squad:'claude-code-mastery', fn:'tech',
    title:'MCP Integration Architect', tagline:'Servidores MCP e composição de ferramentas',
    command:'/claude-code-mastery:agents:mcp-integrator',
    when:'Integrar servidores MCP, compor ferramentas ou expandir capacidades do Claude Code via MCP.' },
  { id:'ccm-conduit',name:'Conduit', icon:'🛠️', squad:'claude-code-mastery', fn:'tech',
    title:'Project Integration Architect', tagline:'CLAUDE.md e integração de projetos',
    command:'/claude-code-mastery:agents:project-integrator',
    when:'Integrar Claude Code em projetos existentes, configurar CLAUDE.md ou setup inicial.' },
  { id:'ccm-vigil',  name:'Vigil',   icon:'🧭', squad:'claude-code-mastery', fn:'tech',
    title:'Roadmap Sentinel', tagline:'Plan-first e roteiro estratégico',
    command:'/claude-code-mastery:agents:roadmap-sentinel',
    when:'Garantir que o trabalho siga um plano antes de executar, ou desenvolver roadmap estratégico.' },
  { id:'ccm-anvil',  name:'Anvil',   icon:'✨', squad:'claude-code-mastery', fn:'tech',
    title:'Skill Craftsman', tagline:'Criar e validar skills para Claude Code',
    command:'/claude-code-mastery:agents:skill-craftsman',
    when:'Criar, editar ou validar skills para Claude Code com metodologia TDD.' },
  { id:'ccm-nexus',  name:'Nexus',   icon:'🕸️', squad:'claude-code-mastery', fn:'tech',
    title:'Swarm Orchestrator', tagline:'Multi-agentes, swarms e execução paralela',
    command:'/claude-code-mastery:agents:swarm-orchestrator',
    when:'Projetar sistemas multi-agente, subagents, padrões de execução paralela e isolamento em worktrees.' },

  /* ── COPY MASTER ─────────────────────────────────────────────── */
  { id:'cm-cyrus',      name:'Cyrus',             icon:'✍️', squad:'copy-master', fn:'copy',
    title:'Copy Master Chief', tagline:'Orquestrador de 32 copywriters especializados',
    command:'/copy-master:agents:copy-master-chief',
    when:'Quando precisar de copy mas não sabe qual especialista usar, ou quando o projeto exige múltiplos.' },
  { id:'cm-hormozi-c',  name:'Alex Hormozi',      icon:'💰', squad:'copy-master', fn:'copy',
    title:'The Offer Architect', tagline:'$100M Offers, Value Equation e CLOSER',
    command:'/copy-master:agents:alex-hormozi',
    when:'Criar ofertas irresistíveis, estrutura Grand Slam Offer ou scripts de venda com CLOSER.' },
  { id:'cm-chaperon',   name:'Andre Chaperon',    icon:'✉️', squad:'copy-master', fn:'copy',
    title:'Email Storytelling Master', tagline:'Soap opera sequences e open loops',
    command:'/copy-master:agents:andre-chaperon',
    when:'Sequências de email que nutrem profundamente, com arcos narrativos e open loops.' },
  { id:'cm-settle',     name:'Ben Settle',        icon:'📧', squad:'copy-master', fn:'copy',
    title:'Daily Email Maverick', tagline:'Personalidade, polarização e infotainment',
    command:'/copy-master:agents:ben-settle',
    when:'Email diário, copy com personalidade, construir audiência fiel através de polarização.' },
  { id:'cm-blair',      name:'Blair Warren',      icon:'🗝️', squad:'copy-master', fn:'copy',
    title:'One Sentence Persuasion', tagline:'5 gatilhos emocionais e copy tribal',
    command:'/copy-master:agents:blair-warren',
    when:'Copy com ressonância emocional profunda, manifestos e copy que constrói movimento.' },
  { id:'cm-voss',       name:'Chris Voss',        icon:'🎙️', squad:'copy-master', fn:'copy',
    title:'FBI Negotiator', tagline:'Empatia tática e diálogo persuasivo',
    command:'/copy-master:agents:chris-voss',
    when:'Copy que parece conversa, lidar com objeções ou páginas de vendas com empatia tática.' },
  { id:'cm-claude-h',   name:'Claude Hopkins',    icon:'🔬', squad:'copy-master', fn:'copy',
    title:'Father of Scientific Advertising', tagline:'Abordagem data-driven e testes',
    command:'/copy-master:agents:claude-hopkins',
    when:'Abordagem científica ao copy, testes A/B e foco em resultados mensuráveis.' },
  { id:'cm-makepeace',  name:'Clayton Makepeace', icon:'💰', squad:'copy-master', fn:'copy',
    title:'Highest-Paid Copywriter', tagline:'Poder emocional com prova — Four-Legged Stool',
    command:'/copy-master:agents:clayton-makepeace',
    when:'Copy com poder emocional ancorado em prova, promoções financeiras ou de saúde.' },
  { id:'cm-kennedy',    name:'Dan Kennedy',       icon:'🎯', squad:'copy-master', fn:'copy',
    title:'No B.S. Direct Response', tagline:'Professor da realidade dura — resposta direta',
    command:'/copy-master:agents:dan-kennedy',
    when:'Conselho sem rodeios, criação de ofertas, cartas de venda, estratégia de preço e direct mail.' },
  { id:'cm-koe',        name:'Dan Koe',           icon:'🧘', squad:'copy-master', fn:'copy',
    title:'One-Person Business Philosopher', tagline:'Conteúdo de deep generalism e creator economy',
    command:'/copy-master:agents:dan-koe',
    when:'Conteúdo short-form que para o scroll, personal brand ou newsletter no ecossistema creator.' },
  { id:'cm-deutsch',    name:'David Deutsch',     icon:'🧩', squad:'copy-master', fn:'copy',
    title:'CopyTHINKING Expert', tagline:'Big Ideas, fascination bullets e ficção no copy',
    command:'/copy-master:agents:david-deutsch',
    when:'Quando o copy precisa de uma Big Idea mais forte ou bullets de fascinação de classe mundial.' },
  { id:'cm-ogilvy',     name:'David Ogilvy',      icon:'🎩', squad:'copy-master', fn:'copy',
    title:'Father of Modern Advertising', tagline:'Branding premium, pesquisa e Big Idea',
    command:'/copy-master:agents:david-ogilvy',
    when:'Copywriting de nível de marca, posicionamento premium ou Big Idea para unificar campanha.' },
  { id:'cm-schwartz',   name:'Eugene Schwartz',   icon:'🧠', squad:'copy-master', fn:'copy',
    title:'Master of Market Awareness', tagline:'Níveis de consciência e copy estratégico',
    command:'/copy-master:agents:eugene-schwartz',
    when:'Diagnosticar níveis de consciência do mercado e criar headlines para cada estágio.' },
  { id:'cm-evaldo',     name:'Evaldo Albuquerque', icon:'💎', squad:'copy-master', fn:'copy',
    title:'One Belief Architect', tagline:'16-Word Sales Letter e copy financeiro',
    command:'/copy-master:agents:evaldo-albuquerque',
    when:'Cartas de vendas com uma única crença central, promoções financeiras e copy de alta conversão.' },
  { id:'cm-kern',       name:'Frank Kern',        icon:'🎸', squad:'copy-master', fn:'copy',
    title:'Mass Control Creator', tagline:'Lifestyle marketing e storytelling de autoridade',
    command:'/copy-master:agents:frank-kern',
    when:'Marketing que converte vendendo estilo de vida, storytelling de autoridade e funis.' },
  { id:'cm-bencivenga', name:'Gary Bencivenga',   icon:'🏆', squad:'copy-master', fn:'copy',
    title:'Greatest Copywriter Alive', tagline:'Copy impecável com provas irrefutáveis',
    command:'/copy-master:agents:gary-bencivenga',
    when:'O mais alto nível de copy — provas irrefutáveis, honestidade como arma e cartas de venda épicas.' },
  { id:'cm-halbert',    name:'Gary Halbert',      icon:'📜', squad:'copy-master', fn:'copy',
    title:'Prince of Print', tagline:'Mala direta, bullets e copy de resposta direta',
    command:'/copy-master:agents:gary-halbert',
    when:'Mala direta, headlines, bullets poderosos e copy de resposta direta arrasador.' },
  { id:'cm-rutz',       name:'Jim Rutz',          icon:'🎯', squad:'copy-master', fn:'copy',
    title:'Magalog Pioneer', tagline:'Formatos longos e copy transformacional',
    command:'/copy-master:agents:jim-rutz',
    when:'Formatos longos como magalogs, copy transformacional e promessas de alto impacto.' },
  { id:'cm-joanna',     name:'Joanna Wiebe',      icon:'💡', squad:'copy-master', fn:'copy',
    title:'Conversion Copywriter', tagline:'CRO-driven copy com voz do cliente',
    command:'/copy-master:agents:joanna-wiebe',
    when:'Copy baseada em voz do cliente, páginas de conversão e A/B testing.' },
  { id:'cm-sugarman',   name:'Joe Sugarman',      icon:'⚡', squad:'copy-master', fn:'copy',
    title:'Triggers Master', tagline:'Slippery slide e 30 psychological triggers',
    command:'/copy-master:agents:joe-sugarman',
    when:'Criar copy que leva o leitor de headline em headline sem parar — Slippery Slide.' },
  { id:'cm-caples',     name:'John Caples',       icon:'🔍', squad:'copy-master', fn:'copy',
    title:'Tested Advertising Methods', tagline:'Headlines testadas e copy que funciona',
    command:'/copy-master:agents:john-caples',
    when:'Headlines testadas, copy baseada em pesquisa e métodos de publicidade que vendem.' },
  { id:'cm-carlton',    name:'John Carlton',      icon:'🐊', squad:'copy-master', fn:'copy',
    title:'The Kick-Ass Copywriter', tagline:'Copy agressivo, street-smart e resposta direta',
    command:'/copy-master:agents:john-carlton',
    when:'Copy agressivo e street-smart, cartas de venda para nichos difíceis e ofertas diretas.' },
  { id:'cm-benson',     name:'Jon Benson',        icon:'🎥', squad:'copy-master', fn:'copy',
    title:'VSL Creator', tagline:'Vídeos de venda e copy conversacional',
    command:'/copy-master:agents:jon-benson',
    when:'Video Sales Letters (VSL), copy conversacional e estrutura de apresentação de venda.' },
  { id:'cm-klaff',      name:'Oren Klaff',        icon:'🎲', squad:'copy-master', fn:'copy',
    title:'Pitch Anything Creator', tagline:'Frame control e persuasão de alto risco',
    command:'/copy-master:agents:oren-klaff',
    when:'Pitch para investidores, controle de frame e persuasão em situações de alto risco.' },
  { id:'cm-parris',     name:'Parris Lampropoulos',icon:'🧬', squad:'copy-master', fn:'copy',
    title:'Health & Financial Copy Master', tagline:'Mecanismo único e copy de nicho especializado',
    command:'/copy-master:agents:parris-lampropoulos',
    when:'Copy de saúde ou finanças, mecanismo único e controles de longa duração.' },
  { id:'cm-cialdini',   name:'Robert Cialdini',   icon:'🔮', squad:'copy-master', fn:'copy',
    title:'Influence & Persuasion Pioneer', tagline:'7 princípios de influência e persuasão ética',
    command:'/copy-master:agents:robert-cialdini',
    when:'Aplicar reciprocidade, escassez, prova social e autoridade no copy de forma ética.' },
  { id:'cm-collier',    name:'Robert Collier',    icon:'📚', squad:'copy-master', fn:'copy',
    title:'Eternal Laws of Selling', tagline:'Copy que entra na conversa da mente',
    command:'/copy-master:agents:robert-collier',
    when:'Entrar na conversa que o prospect já está tendo na cabeça, copy atemporal.' },
  { id:'cm-reeves',     name:'Rosser Reeves',     icon:'🏹', squad:'copy-master', fn:'copy',
    title:'USP Creator', tagline:'Proposta única de venda e copy de impacto',
    command:'/copy-master:agents:rosser-reeves',
    when:'Definir USP (Unique Selling Proposition) e criar copy focado e memorável.' },
  { id:'cm-brunson',    name:'Russell Brunson',   icon:'🚀', squad:'copy-master', fn:'copy',
    title:'ClickFunnels Founder', tagline:'Funis de venda, webinars e perfect webinar script',
    command:'/copy-master:agents:russell-brunson',
    when:'Funis de venda, webinar scripts, one-funnel-away e epiphany bridge stories.' },
  { id:'cm-ry',         name:'Ry Schwartz',       icon:'💫', squad:'copy-master', fn:'copy',
    title:'Coaching Copy Expert', tagline:'Copy para coaches e transformação pessoal',
    command:'/copy-master:agents:ry-schwartz',
    when:'Copy para coaches, consultores e produtos de transformação pessoal.' },
  { id:'cm-sabri',      name:'Sabri Suby',        icon:'🦁', squad:'copy-master', fn:'copy',
    title:'King Kong Founder', tagline:'Sell Like Crazy e geração de leads em escala',
    command:'/copy-master:agents:sabri-suby',
    when:'Escalar geração de leads com copy agressivo, ofertas irresistíveis e funis de conversão.' },
  { id:'cm-georgi',     name:'Stefan Georgi',     icon:'✨', squad:'copy-master', fn:'copy',
    title:'RMBC Method Creator', tagline:'Research-based copy e controles recordistas',
    command:'/copy-master:agents:stefan-georgi',
    when:'Método RMBC (Research, Mechanism, Brief, Copy) para criar controles de alto desempenho.' },
  { id:'cm-brown',      name:'Todd Brown',        icon:'🎓', squad:'copy-master', fn:'copy',
    title:'Marketing Funnel Architect', tagline:'E5 Method e copy de mecanismo único',
    command:'/copy-master:agents:todd-brown',
    when:'E5 Method para criar mecanismos únicos convincentes em funis de marketing.' },

  /* ── CYBERSECURITY ───────────────────────────────────────────── */
  { id:'cyber-chief',    name:'Cyber Chief',       icon:'🛡️', squad:'cybersecurity', fn:'security',
    title:'Cybersecurity Orchestrator', tagline:'Coordenação de avaliações e supervisão ética',
    command:'/cybersecurity:agents:cyber-chief',
    when:'Orientação de segurança abrangente, coordenar avaliação completa ou garantir limites éticos.' },
  { id:'cyber-bust',     name:'Busterer',          icon:'🔍', squad:'cybersecurity', fn:'security',
    title:'Web Content Discovery', tagline:'Enumeração de endpoints e diretórios ocultos',
    command:'/cybersecurity:agents:busterer',
    when:'Descobrir conteúdo web oculto, enumerar diretórios ou encontrar painéis admin.' },
  { id:'cyber-cart',     name:'Cartographer',      icon:'🗺️', squad:'cybersecurity', fn:'security',
    title:'Recon & Attack Surface Mapping', tagline:'Reconhecimento e mapeamento de superfície',
    command:'/cybersecurity:agents:cartographer',
    when:'Mapear superfície de ataque, reconhecimento de rede ou identificar pontos de entrada.' },
  { id:'cyber-sanders',  name:'Chris Sanders',     icon:'📡', squad:'cybersecurity', fn:'security',
    title:'Network Security Monitoring', tagline:'NSM, análise de pacotes e SOC',
    command:'/cybersecurity:agents:chris-sanders',
    when:'Analisar tráfego de rede, configurar monitoramento de segurança ou investigar incidentes.' },
  { id:'cyber-cmd',      name:'Command Generator', icon:'⚡', squad:'cybersecurity', fn:'security',
    title:'Security Tool Command Specialist', tagline:'Sintaxe precisa para ferramentas de segurança',
    command:'/cybersecurity:agents:command-generator',
    when:'Gerar sintaxe exata de comandos para ferramentas de segurança ofensiva e defensiva.' },
  { id:'cyber-dirber',   name:'Dirber',            icon:'📂', squad:'cybersecurity', fn:'security',
    title:'Network Service Enumeration', tagline:'SMB, LDAP, SNMP, RPC e Active Directory',
    command:'/cybersecurity:agents:dirber',
    when:'Enumerar serviços de rede além de web: SMB, LDAP, NFS, RPC ou mapear Active Directory.' },
  { id:'cyber-fuzz',     name:'Fuzzer',            icon:'🎯', squad:'cybersecurity', fn:'security',
    title:'Input Fuzzing Specialist', tagline:'Teste de inputs e pontos de injeção',
    command:'/cybersecurity:agents:fuzzer',
    when:'Testar inputs de aplicações, fazer fuzzing de parâmetros ou encontrar pontos de injeção.' },
  { id:'cyber-georgia',  name:'Georgia Weidman',   icon:'📱', squad:'cybersecurity', fn:'security',
    title:'Mobile Security Expert', tagline:'Segurança mobile e pentest educacional',
    command:'/cybersecurity:agents:georgia-weidman',
    when:'Testar segurança de dispositivos móveis ou aprender pentesting de forma prática.' },
  { id:'cyber-manico',   name:'Jim Manico',        icon:'🔒', squad:'cybersecurity', fn:'security',
    title:'Application Security Expert', tagline:'OWASP e código seguro',
    command:'/cybersecurity:agents:jim-manico',
    when:'Segurança de aplicações web, OWASP Top 10, autenticação segura e prevenção de injeções.' },
  { id:'cyber-marcus',   name:'Marcus Carey',      icon:'🎯', squad:'cybersecurity', fn:'security',
    title:'Security Leadership Expert', tagline:'Times de segurança e inteligência de ameaças',
    command:'/cybersecurity:agents:marcus-carey',
    when:'Construir e liderar times de segurança ou desenvolver programas de inteligência de ameaças.' },
  { id:'cyber-omar',     name:'Omar Santos',       icon:'🎖️', squad:'cybersecurity', fn:'security',
    title:'Vulnerability Management Expert', tagline:'Gestão de vulns, resposta a incidentes e AI security',
    command:'/cybersecurity:agents:omar-santos',
    when:'Gestão de vulnerabilidades, resposta a incidentes ou segurança em sistemas de IA.' },
  { id:'cyber-peter',    name:'Peter Kim',         icon:'🏈', squad:'cybersecurity', fn:'security',
    title:'Red Team Operations Expert', tagline:'Metodologia de pentest e MITRE ATT&CK',
    command:'/cybersecurity:agents:peter-kim',
    when:'Planejar testes de penetração ou operações red team com playbooks de ataque estruturados.' },
  { id:'cyber-rip',      name:'Ripper',            icon:'🔓', squad:'cybersecurity', fn:'security',
    title:'Credential Cracking Specialist', tagline:'Cracking de hashes e avaliação de senhas',
    command:'/cybersecurity:agents:ripper',
    when:'Cracking de hashes, avaliar força de políticas de senhas ou análise de dumps de credenciais.' },
  { id:'cyber-rogue',    name:'Rogue',             icon:'💀', squad:'cybersecurity', fn:'security',
    title:'Exploitation Specialist', tagline:'Exploração e pós-exploração controlada',
    command:'/cybersecurity:agents:rogue',
    when:'Explorar vulnerabilidades confirmadas, demonstrar impacto ou operar em CTF.' },
  { id:'cyber-shannon',  name:'Shannon Runner',    icon:'🔎', squad:'cybersecurity', fn:'security',
    title:'OSINT Specialist', tagline:'Inteligência de fontes abertas',
    command:'/cybersecurity:agents:shannon-runner',
    when:'Coletar inteligência de fontes públicas para avaliações autorizadas ou reconhecimento OSINT.' },

  /* ── DATA SQUAD ──────────────────────────────────────────────── */
  { id:'data-chief',   name:'Datum',           icon:'📊', squad:'data-squad', fn:'data',
    title:'Data Chief Orchestrator', tagline:'Analytics, growth e retenção',
    command:'/data-squad:agents:data-chief',
    when:'Análise de dados, estratégia de crescimento, insights de retenção ou analytics sem especialista definido.' },
  { id:'data-avinash', name:'Avinash Kaushik', icon:'🔍', squad:'data-squad', fn:'data',
    title:'Digital Marketing Evangelist', tagline:'Analytics e KPIs acionáveis',
    command:'/data-squad:agents:avinash-kaushik',
    when:'Construir modelo de medição, KPIs acionáveis, dashboards que geram decisão ou desafiar métricas de vaidade.' },
  { id:'data-spinks',  name:'David Spinks',    icon:'🤝', squad:'data-squad', fn:'movement',
    title:'Community Strategy Pioneer', tagline:'Community-led growth e modelo SPACES',
    command:'/data-squad:agents:david-spinks',
    when:'Construir estratégia de comunidade, medir ROI de comunidade ou aplicar o modelo SPACES.' },
  { id:'data-nick',    name:'Nick Mehta',      icon:'💚', squad:'data-squad', fn:'data',
    title:'Customer Success Pioneer', tagline:'NRR, health scores e prevenção de churn',
    command:'/data-squad:agents:nick-mehta',
    when:'Estratégia de Customer Success, health scores, retenção ou Net Revenue Retention.' },
  { id:'data-peter',   name:'Peter Fader',     icon:'💎', squad:'data-squad', fn:'data',
    title:'CLV Authority', tagline:'Customer lifetime value e customer centricity',
    command:'/data-squad:agents:peter-fader',
    when:'Calcular CLV, segmentação por valor ou construir estratégia genuinamente customer-centric.' },
  { id:'data-sean',    name:'Sean Ellis',      icon:'🚀', squad:'data-squad', fn:'data',
    title:'Growth Hacking Pioneer', tagline:'PMF, North Star Metric e experimentos de crescimento',
    command:'/data-squad:agents:sean-ellis',
    when:'Validar product-market fit, desenhar experimentos de crescimento ou diagnosticar stall de crescimento.' },
  { id:'data-wes',     name:'Wes Kao',         icon:'🎓', squad:'data-squad', fn:'data',
    title:'Cohort Education Strategist', tagline:'Cursos em coorte e audience building',
    command:'/data-squad:agents:wes-kao',
    when:'Projetar cursos em coorte, construir audiência ou criar conteúdo com ponto de vista definido.' },

  /* ── DESIGN SQUAD ─────────────────────────────────────────────── */
  { id:'ds-chief',    name:'Design Chief',         icon:'🎨', squad:'design-squad', fn:'brand',
    title:'Design Operations Orchestrator', tagline:'Roteia para o especialista certo de design',
    command:'/design-squad:agents:design-chief',
    when:'Quando precisar de orientação de design em múltiplos domínios ou coordenar sistemas de design.' },
  { id:'ds-brad',     name:'Brad Frost',           icon:'⚛️', squad:'design-squad', fn:'tech',
    title:'Atomic Design Expert', tagline:'Sistemas de design e metodologia atômica',
    command:'/design-squad:agents:brad-frost',
    when:'Construir design systems do zero, aplicar metodologia atômica ou criar component libraries.' },
  { id:'ds-dan',      name:'Dan Mall',             icon:'🎯', squad:'design-squad', fn:'brand',
    title:'Design Systems at Scale', tagline:'Governança e adoção em organizações',
    command:'/design-squad:agents:dan-mall',
    when:'Escalar design systems, governança ou construir caso de negócio para investimento em design.' },
  { id:'ds-dave',     name:'Dave Malouf',          icon:'⚙️', squad:'design-squad', fn:'brand',
    title:'DesignOps Pioneer', tagline:'Operações e liderança de times de design',
    command:'/design-squad:agents:dave-malouf',
    when:'Estabelecer práticas de DesignOps, gerenciar times de design em escala ou maturidade de design.' },
  { id:'ds-arch',     name:'Design System Architect',icon:'🧩', squad:'design-squad', fn:'tech',
    title:'Component Library Specialist', tagline:'Tokens de design e APIs de componentes',
    command:'/design-squad:agents:design-system-architect',
    when:'Construir component libraries, implementar design tokens ou documentar design systems.' },
  { id:'ds-ui',       name:'UI Engineer',          icon:'💻', squad:'design-squad', fn:'tech',
    title:'Frontend UI Specialist', tagline:'Implementação de UI em código de produção',
    command:'/design-squad:agents:ui-engineer',
    when:'Implementar designs em código, layouts responsivos, animações e performance frontend.' },
  { id:'ds-ux',       name:'UX Designer',          icon:'👤', squad:'design-squad', fn:'brand',
    title:'UX Research & Interaction Design', tagline:'Wireframes, fluxos e testes de usabilidade',
    command:'/design-squad:agents:ux-designer',
    when:'Pesquisa com usuários, arquitetura de informação, wireframes e acessibilidade.' },
  { id:'ds-vis',      name:'Visual Generator',     icon:'🖼️', squad:'design-squad', fn:'brand',
    title:'Visual Asset & AI Image Specialist', tagline:'Conceitos visuais e prompts de IA',
    command:'/design-squad:agents:visual-generator',
    when:'Gerar conceitos visuais, prompts de IA para imagens ou definir identidade visual.' },

  /* ── HORMOZI SQUAD ───────────────────────────────────────────── */
  { id:'hz-chief',     name:'Hormozi Chief',    icon:'🐝', squad:'hormozi-squad', fn:'business',
    title:'Hormozi Squad Orchestrator', tagline:'Roteamento para o especialista Hormozi certo',
    command:'/hormozi-squad:agents:hormozi-chief',
    when:'Qualquer desafio de negócios que precise do framework Hormozi — roteia ao especialista.' },
  { id:'hz-advisor',   name:'Hormozi Advisor',  icon:'🦁', squad:'hormozi-squad', fn:'business',
    title:'Strategic Business Advisor', tagline:'O que o Hormozi faria?',
    command:'/hormozi-squad:agents:hormozi-advisor',
    when:'Conselho estratégico de negócios, platôs de crescimento ou "o que o Hormozi faria?".' },
  { id:'hz-audit',     name:'Hormozi Audit',    icon:'🔍', squad:'hormozi-squad', fn:'business',
    title:'Business Diagnostician', tagline:'Diagnóstico completo do negócio',
    command:'/hormozi-squad:agents:hormozi-audit',
    when:'Avaliar um negócio, identificar o que está quebrado ou preparar para investimento.' },
  { id:'hz-ads',       name:'Hormozi Ads',      icon:'📢', squad:'hormozi-squad', fn:'marketing',
    title:'Paid Advertising Specialist', tagline:'Ads não lucrativos? CPA alto? Criativos cansados?',
    command:'/hormozi-squad:agents:hormozi-ads',
    when:'Ads sem lucro, CPA alto, criativos fatigados ou escalar investimento em anúncios.' },
  { id:'hz-closer',    name:'Hormozi Closer',   icon:'🤝', squad:'hormozi-squad', fn:'business',
    title:'CLOSER Framework Specialist', tagline:'Processo de vendas e objeções',
    command:'/hormozi-squad:agents:hormozi-closer',
    when:'Leads não convertem, ciclo de venda longo, taxa de fechamento baixa ou objeções.' },
  { id:'hz-content',   name:'Hormozi Content',  icon:'📱', squad:'hormozi-squad', fn:'marketing',
    title:'Content Machine Specialist', tagline:'Leads orgânicos e autoridade via conteúdo',
    command:'/hormozi-squad:agents:hormozi-content',
    when:'Leads orgânicos fracos, conteúdo que não converte ou construir sistema de conteúdo.' },
  { id:'hz-copy',      name:'Hormozi Copy',     icon:'✍️', squad:'hormozi-squad', fn:'copy',
    title:'Hormozi-Style Copywriter', tagline:'Copy direto e orientado a valor',
    command:'/hormozi-squad:agents:hormozi-copy',
    when:'Páginas de venda, landing pages ou ad copy no estilo direto e orientado a valor do Hormozi.' },
  { id:'hz-hooks',     name:'Hormozi Hooks',    icon:'🪝', squad:'hormozi-squad', fn:'copy',
    title:'Hook Creation Specialist', tagline:'Headlines, subject lines e primeiras linhas',
    command:'/hormozi-squad:agents:hormozi-hooks',
    when:'Conteúdo sem engajamento, emails não abertos, ads sem cliques ou hooks de alto impacto.' },
  { id:'hz-launch',    name:'Hormozi Launch',   icon:'🚀', squad:'hormozi-squad', fn:'marketing',
    title:'Launch Strategy Specialist', tagline:'Lançar produto, mercado ou do zero',
    command:'/hormozi-squad:agents:hormozi-launch',
    when:'Lançar novo produto, entrar em novo mercado, pré-venda ou construir lista de espera.' },
  { id:'hz-leads',     name:'Hormozi Leads',    icon:'🧲', squad:'hormozi-squad', fn:'marketing',
    title:'$100M Leads Specialist', tagline:'Core 4 de geração de leads',
    command:'/hormozi-squad:agents:hormozi-leads',
    when:'Leads insuficientes, pipeline inconsistente, escalar aquisição ou reduzir custo por lead.' },
  { id:'hz-models',    name:'Hormozi Models',   icon:'🏗️', squad:'hormozi-squad', fn:'business',
    title:'Business Model Designer', tagline:'Modelo de negócio que não escala? Margens baixas?',
    command:'/hormozi-squad:agents:hormozi-models',
    when:'Modelo de negócio errado, margens baixas ou modelo que não escala.' },
  { id:'hz-offers',    name:'Hormozi Offers',   icon:'🎰', squad:'hormozi-squad', fn:'business',
    title:'Grand Slam Offer Architect', tagline:'Criar ou melhorar ofertas irresistíveis',
    command:'/hormozi-squad:agents:hormozi-offers',
    when:'Criar ou melhorar ofertas, conversão baixa, "caro demais" ou construir garantias.' },
  { id:'hz-pricing',   name:'Hormozi Pricing',  icon:'💎', squad:'hormozi-squad', fn:'business',
    title:'Value-Based Pricing Strategist', tagline:'Pare de competir por preço',
    command:'/hormozi-squad:agents:hormozi-pricing',
    when:'Competindo por preço, margens baixas, não consegue cobrar o suficiente ou precificação nova.' },
  { id:'hz-retention', name:'Hormozi Retention',icon:'🔄', squad:'hormozi-squad', fn:'business',
    title:'Churn Reduction Specialist', tagline:'Reduzir churn e maximizar LTV',
    command:'/hormozi-squad:agents:hormozi-retention',
    when:'Churn alto, LTV baixo, clientes saindo após 1-3 meses ou sistemas de retenção fracos.' },
  { id:'hz-scale',     name:'Hormozi Scale',    icon:'📈', squad:'hormozi-squad', fn:'business',
    title:'Business Scaling Specialist', tagline:'Preso em platô? Dono é o gargalo?',
    command:'/hormozi-squad:agents:hormozi-scale',
    when:'Platô de receita, dono como gargalo, operações quebrando ou transição de operador para CEO.' },
  { id:'hz-workshop',  name:'Hormozi Workshop', icon:'🎓', squad:'hormozi-squad', fn:'business',
    title:'Workshop Design Specialist', tagline:'Workshops e eventos como veículos de venda',
    command:'/hormozi-squad:agents:hormozi-workshop',
    when:'Projetar workshops, treinamentos em grupo ou intensivos como veículos de venda.' },

  /* ── MOVEMENT ─────────────────────────────────────────────────── */
  { id:'mv-chief',    name:'Movement Chief',       icon:'✊', squad:'movement', fn:'movement',
    title:'Movement Building Orchestrator', tagline:'Construir, analisar e escalar movimentos',
    command:'/movement:agents:movement-chief',
    when:'Construir, analisar ou escalar um movimento — roteia para os especialistas certos.' },
  { id:'mv-arch',     name:'Movement Architect',   icon:'🏗️', squad:'movement', fn:'movement',
    title:'Community Design Specialist', tagline:'Estrutura de comunidades e escadas de engajamento',
    command:'/movement:agents:movement-architect',
    when:'Projetar estruturas de comunidade, pathways de participação ou governança descentralizada.' },
  { id:'mv-fen',      name:'Fenomenologo',          icon:'🔮', squad:'movement', fn:'movement',
    title:'Phenomenological Analysis Specialist', tagline:'A tensão central que pode alimentar um movimento',
    command:'/movement:agents:fenomenologo',
    when:'Identificar tensão central do movimento, testar se a ideia ressoa com a realidade vivida.' },
  { id:'mv-id',       name:'Identitario',          icon:'🛡️', squad:'movement', fn:'movement',
    title:'Identity Architecture Specialist', tagline:'Valores, símbolos, linguagem e rituais tribais',
    command:'/movement:agents:identitario',
    when:'Projetar sistema de identidade do movimento — quem pertence, marcadores tribais, coesão.' },
  { id:'mv-man',      name:'Manifestador',         icon:'📜', squad:'movement', fn:'story',
    title:'Manifesto Creation Specialist', tagline:'Documento fundador e propagação narrativa',
    command:'/movement:agents:manifestador',
    when:'Escrever o manifesto fundador do movimento ou redesenhar narrativa para nova fase.' },
  { id:'mv-ciclo',    name:'Estrategista de Ciclo', icon:'🔄', squad:'movement', fn:'movement',
    title:'Growth Cycle Strategist', tagline:'Atrair, ativar, sustentar, multiplicar',
    command:'/movement:agents:estrategista-de-ciclo',
    when:'Projetar o motor de crescimento do movimento — quando o momentum está estagnando.' },
  { id:'mv-impacto',  name:'Analista de Impacto',  icon:'📊', squad:'movement', fn:'movement',
    title:'Impact Measurement Specialist', tagline:'Medir impacto real vs atenção gerada',
    command:'/movement:agents:analista-de-impacto',
    when:'Medir se o movimento cria mudança real, projetar frameworks de impacto ou saúde do movimento.' },

  /* ── STORYTELLING ─────────────────────────────────────────────── */
  { id:'st-chief',    name:'Story Chief',       icon:'📖', squad:'storytelling', fn:'story',
    title:'Storytelling Orchestrator', tagline:'Roteia para o especialista narrativo certo',
    command:'/storytelling:agents:story-chief',
    when:'Precisa de ajuda com storytelling mas não sabe qual especialista consultar.' },
  { id:'st-blake',    name:'Blake Snyder',      icon:'🎬', squad:'storytelling', fn:'story',
    title:'Save the Cat Creator', tagline:'Beat Sheet e estrutura comercial de história',
    command:'/storytelling:agents:blake-snyder',
    when:'Estruturar roteiro ou novela com os 15 beats, loglines ou estrutura comercial.' },
  { id:'st-harmon',   name:'Dan Harmon',        icon:'🔄', squad:'storytelling', fn:'story',
    title:'Story Circle Creator', tagline:'Escrita de TV e Story Circle de 8 passos',
    command:'/storytelling:agents:dan-harmon',
    when:'Estruturar episódios de TV, conteúdo episódico ou aplicar o Story Circle.' },
  { id:'st-campbell', name:'Joseph Campbell',   icon:'🏛️', squad:'storytelling', fn:'story',
    title:'Monomyth Creator', tagline:'Hero\'s Journey e mitologia universal',
    command:'/storytelling:agents:joseph-campbell',
    when:'Padrões universais de história, Hero\'s Journey ou conectar narrativa pessoal ao universal.' },
  { id:'st-keith',    name:'Keith Johnstone',   icon:'🎭', squad:'storytelling', fn:'story',
    title:'Impro & Theatresports Creator', tagline:'Espontaneidade, status e narrativa improvisada',
    command:'/storytelling:agents:keith-johnstone',
    when:'Desbloquear criatividade, entender dinâmicas de status ou aplicar pensamento "Yes, And".' },
  { id:'st-kindra',   name:'Kindra Hall',       icon:'💎', squad:'storytelling', fn:'story',
    title:'Business Storytelling Strategist', tagline:'4 histórias que vendem e colam',
    command:'/storytelling:agents:kindra-hall',
    when:'Histórias estratégicas para negócio: vendas, marketing, liderança e Story Gaps.' },
  { id:'st-ganz',     name:'Marshall Ganz',     icon:'✊', squad:'storytelling', fn:'movement',
    title:'Public Narrative Creator', tagline:'Organizar e liderar com narrativa pública',
    command:'/storytelling:agents:marshall-ganz',
    when:'Narrativa para mudança social, ação coletiva, Self-Us-Now ou liderança com autoridade moral.' },
  { id:'st-dicks',    name:'Matthew Dicks',     icon:'🎤', squad:'storytelling', fn:'story',
    title:'Storyworthy Creator', tagline:'O momento de 5 segundos e histórias pessoais',
    command:'/storytelling:agents:matthew-dicks',
    when:'Encontrar e craftar histórias pessoais com o momento de 5 segundos e Homework for Life.' },
  { id:'st-duarte',   name:'Nancy Duarte',      icon:'📊', squad:'storytelling', fn:'story',
    title:'Presentation Storytelling Authority', tagline:'Sparkline e apresentações que movem pessoas',
    command:'/storytelling:agents:nancy-duarte',
    when:'Projetar apresentações com estrutura Sparkline ou transformar dados em narrativa.' },
  { id:'st-klaff',    name:'Oren Klaff',        icon:'🎲', squad:'storytelling', fn:'story',
    title:'Pitch Anything Creator', tagline:'Frame control e pitches de alto risco',
    command:'/storytelling:agents:oren-klaff',
    when:'Pitches para investidores, controle de frame ou persuasão em situações de alto risco.' },
  { id:'st-park',     name:'Park Howell',       icon:'🎯', squad:'storytelling', fn:'story',
    title:'ABT & Story Cycle Creator', tagline:'And But Therefore e Story Cycle de marca',
    command:'/storytelling:agents:park-howell',
    when:'Storytelling de marca, aplicar ABT (And-But-Therefore) ou comunicação com estrutura narrativa.' },
  { id:'st-shawn',    name:'Shawn Coyne',       icon:'📊', squad:'storytelling', fn:'story',
    title:'Story Grid Creator', tagline:'Diagnóstico editorial e comandamentos de história',
    command:'/storytelling:agents:shawn-coyne',
    when:'Diagnosticar por que uma história não funciona, editar cena a cena ou analisar shifts de valor.' },

  /* ── TRAFFIC MASTERS ─────────────────────────────────────────── */
  { id:'tr-chief',    name:'Traffic Chief',      icon:'🎯', squad:'traffic-masters', fn:'marketing',
    title:'Traffic Masters Orchestrator', tagline:'Roteia para o especialista de tráfego certo',
    command:'/traffic-masters:agents:traffic-chief',
    when:'Qualquer desafio de tráfego pago ou mídia — roteia para o especialista.' },
  { id:'tr-midas',    name:'Ad Midas',           icon:'✨', squad:'traffic-masters', fn:'marketing',
    title:'Ad Creative Strategy Specialist', tagline:'Criativos, scripts e briefs',
    command:'/traffic-masters:agents:ad-midas',
    when:'Criar criativos, scripts de anúncio ou briefs — quando os ads não estão gerando cliques.' },
  { id:'tr-analyst',  name:'Ads Analyst',        icon:'🔎', squad:'traffic-masters', fn:'data',
    title:'Ad Account Audit Specialist', tagline:'Auditoria de conta e desperdício de verba',
    command:'/traffic-masters:agents:ads-analyst',
    when:'Auditar conta de anúncios, performance caindo sem causa clara ou gastar sem resultado.' },
  { id:'tr-creative', name:'Creative Analyst',   icon:'🔬', squad:'traffic-masters', fn:'marketing',
    title:'Ad Creative Performance Analyst', tagline:'Quais criativos funcionam e por quê',
    command:'/traffic-masters:agents:creative-analyst',
    when:'Analisar criativos, identificar padrões de performance ou quando o criativo está fatigado.' },
  { id:'tr-depesh',   name:'Depesh Mandalia',    icon:'📐', squad:'traffic-masters', fn:'marketing',
    title:'BPM Method Creator', tagline:'Escalar Facebook Ads com estrutura sistemática',
    command:'/traffic-masters:agents:depesh-mandalia',
    when:'Escalar Facebook/Meta Ads de 5 para 6-7 dígitos com o BPM Method e CBO estruturado.' },
  { id:'tr-fiscal',   name:'Fiscal',             icon:'💰', squad:'traffic-masters', fn:'business',
    title:'Ad Budget & Financial Manager', tagline:'Orçamentos, ROAS e fluxo de caixa para ads',
    command:'/traffic-masters:agents:fiscal',
    when:'Definir orçamento de anúncios, gerenciar fluxo de caixa ou calcular metas de ROAS.' },
  { id:'tr-kasim',    name:'Kasim Aslam',        icon:'🔍', squad:'traffic-masters', fn:'marketing',
    title:'Google Ads Authority', tagline:'Performance Max, Search e "You vs. Google"',
    command:'/traffic-masters:agents:kasim-aslam',
    when:'Google Ads, otimizar Performance Max ou aplicar o framework adversarial "You vs. Google".' },
  { id:'tr-buyer',    name:'Media Buyer',        icon:'🖥️', squad:'traffic-masters', fn:'marketing',
    title:'Cross-Platform Media Buyer', tagline:'Setup, otimização diária e multi-plataforma',
    command:'/traffic-masters:agents:media-buyer',
    when:'Configurar campanhas, gerenciar otimização diária ou gerenciar campanhas multi-plataforma.' },
  { id:'tr-molly',    name:'Molly Pittman',      icon:'👑', squad:'traffic-masters', fn:'marketing',
    title:'The Conversion Queen', tagline:'Facebook Ads e Ad Grid para e-commerce',
    command:'/traffic-masters:agents:molly-pittman',
    when:'Construir sistemas de anúncios Facebook do zero com Ad Grid e estratégia de temperatura.' },
  { id:'tr-nicholas', name:'Nicholas Kusmich',   icon:'🎯', squad:'traffic-masters', fn:'marketing',
    title:'Contextual Congruence Pioneer', tagline:'Ads nativos com alto ROI para personal brands',
    command:'/traffic-masters:agents:nicholas-kusmich',
    when:'Facebook Ads que parecem nativos, filosofia Give-Give-Give-Ask para coaches/consultores.' },
  { id:'tr-pedro',    name:'Pedro Sobral',       icon:'🥷', squad:'traffic-masters', fn:'marketing',
    title:'Ninja Supremo do Tráfego', tagline:'Meta Ads no mercado brasileiro e LATAM',
    command:'/traffic-masters:agents:pedro-sobral',
    when:'Gestão de tráfego para mercados BR/LATAM, Meta Ads em português e formação de gestores.' },
  { id:'tr-perf',     name:'Performance Analyst',icon:'📊', squad:'traffic-masters', fn:'data',
    title:'Campaign Data Analyst', tagline:'Análise de performance e relatórios',
    command:'/traffic-masters:agents:performance-analyst',
    when:'Analisar performance de campanhas, construir dashboards ou decidir com base em dados.' },
  { id:'tr-pixel',    name:'Pixel Specialist',   icon:'🔌', squad:'traffic-masters', fn:'marketing',
    title:'Tracking & Attribution Specialist', tagline:'Pixels, conversões e rastreamento server-side',
    command:'/traffic-masters:agents:pixel-specialist',
    when:'Rastreamento quebrado, dados imprecisos, mudanças iOS/privacidade ou tracking server-side.' },
  { id:'tr-ralph',    name:'Ralph Burns',        icon:'🎙️', squad:'traffic-masters', fn:'marketing',
    title:'Performance Marketing Pioneer', tagline:'Full-funnel paid social e nCAC/MER',
    command:'/traffic-masters:agents:ralph-burns',
    when:'Estratégia full-funnel, análise nCAC/MER ou escalar negócios com propósito.' },
  { id:'tr-scale',    name:'Scale Optimizer',    icon:'🚀', squad:'traffic-masters', fn:'marketing',
    title:'Campaign Scaling Specialist', tagline:'Escalar verba sem CPA explosivo',
    command:'/traffic-masters:agents:scale-optimizer',
    when:'Escalar investimento em anúncios, CPA aumenta com budget ou diminishing returns.' },
  { id:'tr-tom',      name:'Tom Breeze',         icon:'🎬', squad:'traffic-masters', fn:'marketing',
    title:'YouTube Ads Authority', tagline:'ADUCATE Formula e publicidade baseada em intenção',
    command:'/traffic-masters:agents:tom-breeze',
    when:'Anúncios no YouTube, scripts de vídeo, funis YouTube ou campanhas TrueView.' },
];
