const CATS_META = {
  planejar:     { name: 'Planejar',        icon: '🧠', color: '#a78bfa' },
  implementar:  { name: 'Implementar',     icon: '⚙️', color: '#60a5fa' },
  revisar:      { name: 'Debug & Review',  icon: '🔍', color: '#f87171' },
  design:       { name: 'Design & UI',     icon: '🎨', color: '#f472b6' },
  escrever:     { name: 'Copywriting',     icon: '✍️', color: '#fbbf24' },
  browser:      { name: 'Browser & Testes',icon: '🌐', color: '#34d399' },
  dados:        { name: 'Dados & Scraping',icon: '📊', color: '#fb923c' },
  produtividade:{ name: 'Produtividade',   icon: '⚡', color: '#22d3ee' },
};
const CATS_ORDER = ['planejar','implementar','revisar','design','escrever','browser','dados','produtividade'];

const SKILLS_DB = {
  brainstorming: {
    id:'brainstorming', name:'Brainstorming', command:'/brainstorming', plugin:'superpowers', catId:'planejar',
    tagline:'Ideias → specs aprovadas antes de qualquer código',
    desc:'Transforma ideias brutas em designs completos via diálogo colaborativo. Nenhum código antes da aprovação.',
    stats:[{value:'7',label:'etapas no checklist'},{value:'2–3',label:'abordagens propostas'},{value:'0',label:'código antes da aprovação'}],
    without:['Começa a codar sem entender o problema real','Descobre requisitos críticos no meio do desenvolvimento','Reescreve código por falta de alinhamento inicial','Decisões de arquitetura tomadas impulsivamente'],
    with:['Spec completa e aprovada antes de qualquer código','Trade-offs mapeados com decisão consciente','Design doc salvo em docs/superpowers/specs/','Zero retrabalho por falta de alinhamento'],
    example:{before:'// "Vou implementar o sistema de notificações..."\n// (sem saber se é push, email ou in-app)',after:'✓ Spec aprovada: notificações in-app com badge\n✓ Push só para eventos críticos\n✓ Implementando com TDD...'},
  },
  'writing-plans': {
    id:'writing-plans', name:'Escrever Plano', command:'/writing-plans', plugin:'superpowers', catId:'planejar',
    tagline:'Plano de implementação com tasks, arquivos e testes',
    desc:'Cria plano completo com tasks granulares, arquivos mapeados e instruções de teste — antes de tocar em código.',
    stats:[{value:'DRY',label:'princípio aplicado'},{value:'YAGNI',label:'escopo controlado'},{value:'TDD',label:'testes primeiro'}],
    without:['Implementação sem clareza dos arquivos a modificar','Tasks grandes e vagas que não terminam','Testes pensados depois — cobertura fraca','Escopo que cresce sem controle'],
    with:['Todos os arquivos mapeados antes de começar','Tasks granulares e verificáveis','Instruções de teste escritas junto com a task','Escopo definido — sem feature creep'],
    example:{before:'// Tarefa: "implementar autenticação"\n// (sem saber quais arquivos, etapas ou como testar)',after:'## Plano: Auth\n1. middleware jwt.ts — testar com jest\n2. POST /auth/login — testar 401/200\n3. guard authRequired — testar rotas protegidas'},
  },
  'make-plan': {
    id:'make-plan', name:'Make Plan', command:'/make-plan', plugin:'thedotmack', catId:'planejar',
    tagline:'Plano faseado com descoberta prévia de docs e APIs reais',
    desc:'Lê documentação real antes de planejar. Subagents coletam fatos e produzem plano executável em contextos separados.',
    stats:[{value:'Fase 0',label:'descoberta obrigatória'},{value:'100%',label:'APIs verificadas'},{value:'multi',label:'sessões suportadas'}],
    without:['Plano baseado em APIs que o agente "acha que existem"','Descobertas surpresa no meio da implementação','Plano que não funciona em sessões separadas','Subagents sem contexto suficiente'],
    with:['Fase 0 garante que docs foram lidos antes do plano','Assinaturas exatas de funções verificadas','Plano executável em novos contextos sem perda','Zero suposições — apenas fatos verificados'],
    example:{before:'useFetch("/api/users") // ← API que talvez nem exista',after:'## Fase 0: Descoberta\n✓ GET /api/users existe — retorna UserSummary[]\n✓ Auth: Bearer token no header\n## Fase 1: Implementar...'},
  },
  'executing-plans': {
    id:'executing-plans', name:'Executar Plano', command:'/executing-plans', plugin:'superpowers', catId:'planejar',
    tagline:'Executa plano passo a passo com checkpoints e evidências',
    desc:'Carrega um plano escrito, revisa criticamente, executa cada task em ordem e reporta progresso.',
    stats:[{value:'1 por 1',label:'tasks executadas'},{value:'✓',label:'verificação por task'},{value:'0',label:'tasks puladas'}],
    without:['Executa de cabeça e perde o fio do plano','Tasks grandes viram trabalho parcial','Sem checkpoint — difícil retomar depois','Progresso não comunicado claramente'],
    with:['Cada task marcada com evidência de conclusão','Questões levantadas antes de iniciar','Progresso visível e rastreável por task','Fácil de retomar em nova sessão'],
    example:{before:'// Tentando lembrar onde parou...\n// O que falta fazer mesmo?',after:'[✓] Task 1: schema — done\n[✓] Task 2: migration — done\n[→] Task 3: endpoint POST /leads'},
  },
  'planning-with-files-zh': {
    id:'planning-with-files-zh', name:'Planning (Arquivos)', command:'/planning-with-files-zh', plugin:'planning-with-files-zh', catId:'planejar',
    tagline:'Arquivos de progresso para rastrear tarefas entre sessões',
    desc:'Cria task_plan.md, findings.md e progress.md. Retomada automática ao detectar plano ativo na próxima sessão.',
    stats:[{value:'3',label:'arquivos de controle'},{value:'auto',label:'retomada de sessão'},{value:'∞',label:'sessões suportadas'}],
    without:['Contexto perdido ao iniciar nova sessão','Precisa re-explicar o que estava fazendo','Progresso não registrado — retrabalho frequente','Difícil saber o que falta fazer'],
    with:['task_plan.md sempre atualizado','progress.md registra cada ação','Retomada automática ao detectar plano ativo','Qualquer sessão nova continua de onde parou'],
    example:{before:'// Nova sessão...\n// Que era mesmo o que eu estava fazendo ontem?',after:'[planning] Plano ativo detectado!\nÚltimo passo: endpoint POST /leads\nPróximo: criar testes unitários'},
  },
  'test-driven-development': {
    id:'test-driven-development', name:'TDD', command:'/test-driven-development', plugin:'superpowers', catId:'implementar',
    tagline:'Teste primeiro. Sem exceção.',
    desc:'Aplica o ciclo RED→GREEN→REFACTOR rigorosamente. Nenhum código de produção sem um teste que falha primeiro.',
    stats:[{value:'RED',label:'teste falha primeiro'},{value:'GREEN',label:'código mínimo'},{value:'REFACTOR',label:'melhoria segura'}],
    without:['Testes escritos depois — cobrem só o que foi feito','Bugs descobertos em produção','Refatorações arriscadas sem rede de segurança','Incerteza se o código realmente funciona'],
    with:['Cada comportamento provado antes da implementação','Bugs detectados no momento em que surgem','Refatoração segura com suite cobrindo','Confiança total no código entregue'],
    example:{before:'// Implementa a função primeiro...\nfunction calcDiscount(price) {\n  return price * 0.9; // parece certo?\n}',after:'// RED: teste falhando\nexpect(calcDiscount(100)).toBe(90);\n// GREEN: implementação mínima\nfunction calcDiscount(p) { return p * 0.9; }\n// ✓ PASSA'},
  },
  'subagent-driven-development': {
    id:'subagent-driven-development', name:'Subagent Dev', command:'/subagent-driven-development', plugin:'superpowers', catId:'implementar',
    tagline:'Um subagent fresco por task + revisão dupla',
    desc:'Executa planos despachando um subagent isolado por task, com revisão em dois estágios após cada entrega.',
    stats:[{value:'1',label:'subagent por task'},{value:'2',label:'estágios de revisão'},{value:'0',label:'contexto herdado'}],
    without:['Contexto acumula e agente perde foco','Tasks longas numa sessão — erros se propagam','Sem revisão sistemática — problemas passam','Difícil manter qualidade em projetos grandes'],
    with:['Cada subagent começa fresco com contexto preciso','Revisão de spec + qualidade após cada task','Problemas detectados cedo antes de propagar','Qualidade consistente independente do tamanho'],
    example:{before:'// 50 mensagens depois, o agente esqueceu o requisito inicial...',after:'→ Subagent 1: endpoint POST /leads [✓ revisado]\n→ Subagent 2: testes unitários [✓ revisado]\n→ Subagent 3: migration [✓ revisado]'},
  },
  'dispatching-parallel-agents': {
    id:'dispatching-parallel-agents', name:'Parallel Agents', command:'/dispatching-parallel-agents', plugin:'superpowers', catId:'implementar',
    tagline:'Múltiplas tarefas independentes em paralelo',
    desc:'Identifica tarefas independentes e as delega para subagents simultâneos, reduzindo drasticamente o tempo total.',
    stats:[{value:'N×',label:'tarefas em paralelo'},{value:'0',label:'dependências cruzadas'},{value:'-70%',label:'tempo estimado'}],
    without:['Tarefas independentes executadas sequencialmente','Tempo total = soma de todos os tempos','Sessão única acumula contexto de vários domínios','Um gargalo bloqueia todas as demais'],
    with:['Tarefas independentes executam simultaneamente','Tempo total = tempo da task mais longa','Cada subagent focado no seu domínio','Investigações paralelas sem interferência'],
    example:{before:'// Fix A (20min) → Fix B (20min) → Fix C (20min) = 60min',after:'→ Agent A: fix auth [paralelo]\n→ Agent B: fix billing [paralelo]\n→ Agent C: fix notif [paralelo]\n// Tempo total: ~20min'},
  },
  do: {
    id:'do', name:'Do (Orquestrador)', command:'/do', plugin:'thedotmack', catId:'implementar',
    tagline:'Orquestra execução faseada — você coordena, subagents executam',
    desc:'Você é o orquestrador. Delega toda a implementação para subagents e só coordena, verifica evidências e avança de fase.',
    stats:[{value:'3',label:'tipos de subagent'},{value:'100%',label:'evidências exigidas'},{value:'0',label:'código no orquestrador'}],
    without:['Orquestrador faz a implementação e perde o fio','Sem verificação estruturada de cada fase','Anti-patterns passam sem verificar','Difícil manter visão geral em projetos grandes'],
    with:['Impl, verificação e anti-patterns em subagents separados','Cada fase avança só com evidências confirmadas','Orquestrador mantém visão geral sem se perder','Qualidade garantida em cada fase'],
    example:{before:'// Implementação + tests + review tudo na mesma sessão misturado',after:'→ [Impl] Subagent cria endpoint\n→ [Verif] Subagent roda testes\n→ [Anti] Subagent checa bad patterns\n→ ✓ Fase aprovada'},
  },
  'using-git-worktrees': {
    id:'using-git-worktrees', name:'Git Worktrees', command:'/using-git-worktrees', plugin:'superpowers', catId:'implementar',
    tagline:'Branches isoladas sem interromper o trabalho atual',
    desc:'Cria git worktrees com seleção inteligente de diretório — múltiplas branches simultâneas sem git stash.',
    stats:[{value:'N',label:'branches simultâneas'},{value:'0',label:'git stash necessário'},{value:'safe',label:'verificação antes de criar'}],
    without:['Stash de trabalho para trocar de branch','Branches conflitam com trabalho em progresso','Impossível testar duas features ao mesmo tempo','Erros ao criar worktree no diretório errado'],
    with:['Feature nova em worktree isolado sem afetar o atual','Múltiplas branches ativas simultaneamente','Sem stash — cada worktree tem seu working tree','Diretório selecionado com verificação de segurança'],
    example:{before:'$ git stash\n$ git checkout -b feature/nova\n// Trabalho atual perdido do contexto...',after:'$ git worktree add .worktrees/nova feature/nova\n// Continua no branch atual E trabalha na nova feature'},
  },
  'writing-skills': {
    id:'writing-skills', name:'Criar Skills', command:'/writing-skills', plugin:'superpowers', catId:'implementar',
    tagline:'Criar skills para Claude Code com metodologia TDD',
    desc:'Aplica TDD à criação de documentação de processo. Testa o comportamento sem a skill antes de escrever.',
    stats:[{value:'TDD',label:'para documentação'},{value:'SKILL.md',label:'arquivo de saída'},{value:'3',label:'fases: RED/GREEN/REFACTOR'}],
    without:['Skill escrita sem testar se realmente funciona','Agente ignora a skill por estar mal estruturada','Brechas que permitem racionalizar e pular a skill','Skill que descreve o quê mas não o como'],
    with:['Testa agente sem a skill (RED) antes de escrever','Garante que a skill causa o comportamento desejado','Fecha brechas de racionalização no REFACTOR','Skill que o agente realmente segue'],
    example:{before:'// Escrevendo skill de debugging...\n// "Parece boa? Vamos publicar!"',after:'// RED: agente sem skill faz patch sem causa raiz\n// GREEN: skill escrita com regra explícita\n// REFACTOR: fechada a brecha "mas esse é simples"'},
  },
  'version-bump': {
    id:'version-bump', name:'Version Bump', command:'/version-bump', plugin:'thedotmack', catId:'implementar',
    tagline:'Release completo: versão, tag, GitHub Release automatizados',
    desc:'Incrementa versão em todos os arquivos, builda, commita, cria tag annotated e publica GitHub Release com changelog.',
    stats:[{value:'3',label:'arquivos versionados'},{value:'auto',label:'tag + release criados'},{value:'0',label:'passos manuais'}],
    without:['Versão desatualizada em package.json mas não em plugin.json','Release sem tag — impossível rastrear no histórico','CHANGELOG desatualizado ou inexistente','Processo de release lento e propenso a erro'],
    with:['Versão sincronizada em todos os arquivos','Tag annotated criada e empurrada','GitHub Release publicado com release notes','CHANGELOG.md regenerado via GitHub API'],
    example:{before:'$ vim package.json  # bump\n$ vim marketplace.json  # bump\n$ git tag v1.2.3\n$ gh release create... # esqueci a flag',after:'/version-bump → MINOR\n✓ package.json → 1.2.0\n✓ marketplace.json → 1.2.0\n✓ tag v1.2.0 criada\n✓ GitHub Release publicado'},
  },
  'systematic-debugging': {
    id:'systematic-debugging', name:'Debug Sistemático', command:'/systematic-debugging', plugin:'superpowers', catId:'revisar',
    tagline:'Causa raiz antes de qualquer correção — sem exceção',
    desc:'Lei de ferro: nenhum fix sem investigação de causa raiz. Fases: reproduzir → isolar → identificar → corrigir.',
    stats:[{value:'4',label:'fases de investigação'},{value:'0',label:'patches de sintoma'},{value:'100%',label:'causa raiz identificada'}],
    without:['Tenta fix aleatório — às vezes funciona, às vezes não','Mesmo bug volta com sintoma diferente dias depois','Patches de sintoma que mascaram o problema real','Bugs que "desaparecem" e reaparecem misteriosamente'],
    with:['Bug reproduzido de forma controlada','Causa raiz identificada com evidências concretas','Correção cirúrgica — não afeta comportamento não relacionado','Bug nunca volta porque a raiz foi eliminada'],
    example:{before:'// Token expirando aleatoriamente...\n// Tentativa 1: aumentar TTL para 7 dias\n// (bug continua)',after:'// Fase 1: reproduzir — acontece após 1h exata\n// Fase 2: isolar — só em produção\n// Fase 3: causa raiz — timezone no servidor\n// Fix preciso e cirúrgico ✓'},
  },
  'requesting-code-review': {
    id:'requesting-code-review', name:'Solicitar Review', command:'/requesting-code-review', plugin:'superpowers', catId:'revisar',
    tagline:'Subagent revisor com contexto isolado e imparcial',
    desc:'Despacha o agente code-reviewer com contexto preciso — sem herdar histórico da sessão. Revisão objetiva a cada feature.',
    stats:[{value:'0',label:'contexto herdado'},{value:'2',label:'SHAs passados ao revisor'},{value:'3',label:'momentos obrigatórios'}],
    without:['Código entregue sem revisão — bugs chegam em produção','Auto-revisão do mesmo agente — viés total','Issues detectados tarde — custo alto de correção','Sem padrão de qualidade consistente'],
    with:['Revisor com visão fresca e sem viés','Contexto cirúrgico: só o diff relevante','Revisão obrigatória após tasks e antes de merge','Qualidade consistente em toda a codebase'],
    example:{before:'// "Acabei de implementar. Parece certo para mim, vou fazer merge!"',after:'→ Despachando code-reviewer\n→ BASE: abc123 | HEAD: def456\n→ Revisor: 2 edge cases não cobertos\n→ Corrigindo antes do merge'},
  },
  'receiving-code-review': {
    id:'receiving-code-review', name:'Receber Review', command:'/receiving-code-review', plugin:'superpowers', catId:'revisar',
    tagline:'Avaliação técnica rigorosa — não performativa',
    desc:'Trata feedback com rigor técnico. Verifica antes de implementar. Questiona sugestões incorretas com fundamentação.',
    stats:[{value:'6',label:'etapas de avaliação'},{value:'0',label:'"você está certo!" sem verificar'},{value:'100%',label:'sugestões verificadas'}],
    without:['"Você está certo!" sem verificar','Implementa todas as sugestões sem questionar','Aceita feedback por educação, não por mérito','Sugestão errada implementada — novo bug introduzido'],
    with:['Cada sugestão verificada na codebase','Pushback técnico quando a sugestão está errada','Implementação uma de cada vez com teste','Qualidade não comprometida por pressão social'],
    example:{before:'// Revisor: "use useCallback aqui"\n// Agente: "Ótima sugestão! Implementando..."',after:'// Revisor: "use useCallback aqui"\n// Verificando: referência estável necessária?\n// Não — componente não passa para filhos\n// Resposta: "não é necessário porque..."'},
  },
  'verification-before-completion': {
    id:'verification-before-completion', name:'Verificação Final', command:'/verification-before-completion', plugin:'superpowers', catId:'revisar',
    tagline:'Evidências antes de qualquer afirmação de sucesso',
    desc:'Lei de ferro: proibido afirmar "pronto" sem evidência recente de verificação. Identifica e roda o comando que prova.',
    stats:[{value:'0',label:'"pronto" sem evidência'},{value:'1',label:'comando de verificação'},{value:'100%',label:'claims com prova'}],
    without:['"Implementado! Deve estar passando" — sem checar','Bug descoberto pelo usuário que foi declarado resolvido','PR mergeado com testes falhando "por descuido"','Confiança quebrada por declarações falsas'],
    with:['Comando de verificação rodado no mesmo turno','Output real do teste mostrado como evidência','Zero claims sem prova — confiança total','Problemas detectados antes de declarar pronto'],
    example:{before:'// "Implementei o fix de auth. Deve estar funcionando!"',after:'$ npm test auth.spec.ts\n✓ should reject invalid token (2ms)\n✓ should accept valid token (1ms)\n// Evidência confirmada → ✓ pronto'},
  },
  'finishing-a-development-branch': {
    id:'finishing-a-development-branch', name:'Fechar Branch', command:'/finishing-a-development-branch', plugin:'superpowers', catId:'revisar',
    tagline:'Testes → opções de integração → limpeza automática',
    desc:'Verifica testes, apresenta opções de merge/PR/squash e faz limpeza de worktrees e branches temporárias.',
    stats:[{value:'3',label:'opções de integração'},{value:'0',label:'branches sujas deixadas'},{value:'100%',label:'testes passando antes'}],
    without:['Merge antes de verificar se testes passam','Worktrees e branches acumulando no repo','Incerteza sobre qual estratégia de merge usar','Histórico de git poluído com commits de trabalho'],
    with:['Testes verificados antes de qualquer decisão','Opções claras: merge direto, PR, squash','Limpeza automática de worktree e branches','Histórico de git limpo e semântico'],
    example:{before:'// "Acho que está pronto... vou fazer merge na mão"',after:'✓ npm test: 47 passing\nOpções:\n1. Merge direto em main\n2. Abrir PR com description\n3. Squash commit\n→ PR #42 aberto, worktree limpo'},
  },
  'smart-explore': {
    id:'smart-explore', name:'Smart Explore', command:'/smart-explore', plugin:'thedotmack', catId:'revisar',
    tagline:'Exploração de código via AST — -80% tokens',
    desc:'Substitui Read/Grep/Glob por smart_search/outline/unfold via tree-sitter. Indexa estrutura antes de carregar implementação.',
    stats:[{value:'-80%',label:'tokens gastos'},{value:'AST',label:'análise estrutural'},{value:'3',label:'camadas de exploração'}],
    without:['Lê arquivos inteiros para encontrar uma função','Grep retorna contexto irrelevante','Tokens desperdiçados carregando código não necessário','Codebase grande esgota o contexto'],
    with:['smart_search descobre arquivos e símbolos em uma chamada','smart_outline mostra estrutura sem carregar implementação','smart_unfold carrega só o símbolo específico','Contexto preservado para o trabalho que importa'],
    example:{before:'// Read auth.ts (800 linhas)\n// Read user.ts (600 linhas)\n// Grep "validateToken" — 40 resultados',after:'smart_search("validateToken", "./src")\n→ auth/jwt.ts:45 validateToken()\nsmart_unfold("auth/jwt.ts", "validateToken")\n→ 12 linhas relevantes ✓'},
  },
  'frontend-design': {
    id:'frontend-design', name:'Frontend Design', command:'/frontend-design', plugin:'frontend-design', catId:'design',
    tagline:'Interfaces memoráveis — zero estética genérica de IA',
    desc:'Cria interfaces de produção com direção estética clara. Define o conceito visual antes de codificar.',
    stats:[{value:'0',label:'Inter / Roboto / Arial'},{value:'1',label:'direção estética definida'},{value:'∞',label:'estilos possíveis'}],
    without:['Cards brancos com sombra e botões azuis — toda IA faz igual','Tipografia genérica sem personalidade','Layout previsível que não diferencia o produto','Visual que parece "feito por IA" à primeira vista'],
    with:['Direção estética definida e executada com precisão','Tipografia única e contextual','Layout que o usuário vai lembrar','Código de produção funcional e visualmente marcante'],
    example:{before:'// Inter, cards brancos, botão #3B82F6\n// "Parece qualquer SaaS genérico..."',after:'// Direção: editorial + terminal\n// Syne (display) + JetBrains Mono\n// Quase-preto + cyan elétrico\n// Dot grid + glassmorphism'},
  },
  'ui-ux-pro-max': {
    id:'ui-ux-pro-max', name:'UI/UX Pro Max', command:'/ui-ux-pro-max', plugin:'ui-ux-pro-max', catId:'design',
    tagline:'161 paletas, 57 pares de fontes e 99 diretrizes de UX',
    desc:'Biblioteca completa de referências de design com 50+ estilos, 161 paletas, 57 pares de fontes e 99 diretrizes para 10 stacks.',
    stats:[{value:'161',label:'paletas de cores'},{value:'57',label:'pares de fontes'},{value:'99',label:'diretrizes de UX'}],
    without:['Escolhas de design sem referência — resultado inconsistente','Paleta aleatória sem harmonia','Acessibilidade ignorada','Componentes que não conversam entre si'],
    with:['Paleta escolhida com critério de harmonia e contexto','Par de fontes com hierarquia visual clara','Diretrizes de UX aplicadas sistematicamente','Design consistente em toda a interface'],
    example:{before:'// Cor do botão: #FF5722 "porque parece legal"',after:'// Contexto: SaaS B2B conservador\n// Paleta: azul profundo + cinza\n// Fonte: DM Sans + Syne\n// Contraste WCAG AA ✓'},
  },
  'figma-implement-design': {
    id:'figma-implement-design', name:'Figma → Código', command:'/figma-implement-design', plugin:'figma-implement-design', catId:'design',
    tagline:'Fidelidade 1:1 entre design Figma e código',
    desc:'Lê arquivos Figma via MCP server para extrair tokens de design e gera código pixel-perfect.',
    stats:[{value:'1:1',label:'fidelidade visual'},{value:'MCP',label:'acesso ao Figma'},{value:'0',label:'suposições visuais'}],
    without:['Implementa o design de memória com aproximações','Spacing, cores e fontes levemente diferentes do Figma','Vai e volta entre Figma e código para ajustar','Design aprovado ≠ produto entregue fielmente'],
    with:['Tokens extraídos direto do arquivo Figma via MCP','Spacing, radius, cores e fontes exatos','Zero idas e vindas para ajuste visual','Design aprovado = produto entregue fielmente'],
    example:{before:'// color: "#3b82f6" (aproximação do que vi no Figma)',after:'// Figma token: brand-primary = #3A7BFF\n// Spacing: 24px (grid base-6)\n// DM Sans 500 16px/1.5\n// ← extraído direto do arquivo'},
  },
  'vercel-react-best-practices': {
    id:'vercel-react-best-practices', name:'Vercel React', command:'/vercel-react-best-practices', plugin:'vercel-react', catId:'design',
    tagline:'70 regras de performance React/Next.js da Vercel Engineering',
    desc:'Boas práticas da Vercel para React e Next.js — 70 regras em 8 categorias priorizadas por impacto.',
    stats:[{value:'70',label:'regras de performance'},{value:'8',label:'categorias'},{value:'CRÍTICO',label:'waterfalls eliminados'}],
    without:['Waterfalls de dados causam loading lento em cascata','Bundle gigante por imports desnecessários','Dados buscados no cliente quando deveriam estar no server','Performance inconsistente'],
    with:['Waterfalls eliminados com parallel data fetching','Bundle otimizado com code splitting','Server components usados onde fazem sentido','Performance consistente com padrões Vercel'],
    example:{before:'// Client component busca user, depois posts, depois comments\n// 3 waterfalls = 3× mais lento',after:'// Server component com Promise.all([\n//   getUser(), getPosts(), getComments()\n// ]) — paralelo ✓'},
  },
  copywriting: {
    id:'copywriting', name:'Copywriting', command:'/copywriting', plugin:'copywriting', catId:'escrever',
    tagline:'Copy que persuade e converte visitantes em clientes',
    desc:'Escreve copy de marketing baseado na persona real: problema, objeções e linguagem do cliente. Para homepages, landing pages e mais.',
    stats:[{value:'6+',label:'tipos de página'},{value:'1',label:'ação primária por página'},{value:'100%',label:'foco no cliente'}],
    without:['Copy genérico que fala do produto, não do cliente','Headline fraca que não para o scroll','CTA vago: "Saiba mais"','Benefícios listados sem conectar ao problema real'],
    with:['Headline que fala direto com a dor do cliente','Copy na linguagem que o cliente usa','CTA específico e orientado à conversão','Estrutura que guia o visitante até a ação'],
    example:{before:'"Bem-vindo ao FlowCRM. Nossa plataforma tem muitas funcionalidades incríveis para o seu negócio."',after:'"Feche mais negócios sem perder o controle do funil.\nPara times de vendas que odeiam planilha."'},
  },
  humanizer: {
    id:'humanizer', name:'Humanizer', command:'/humanizer', plugin:'humanizer', catId:'escrever',
    tagline:'Texto que soa humano — remove padrões de escrita de IA',
    desc:'Remove padrões identificados pelo guia Wikipedia "Signs of AI writing": em dash excessivo, voz passiva, filler phrases e mais.',
    stats:[{value:'10+',label:'padrões de IA detectados'},{value:'0',label:'filler phrases restantes'},{value:'100%',label:'substância preservada'}],
    without:['"É importante notar que..." — filler clássico de IA','Em dash (—) overuse em toda frase','Regra dos três: listas de exatamente 3 itens sempre','Texto que parece gerado por IA à primeira leitura'],
    with:['Texto fluido sem marcadores de geração automática','Filler phrases removidos — só substância','Voz ativa e direta sem hedging desnecessário','Leitura natural que ninguém identifica como IA'],
    example:{before:'"É importante notar que esta funcionalidade — desenvolvida com muito cuidado — oferece três benefícios: velocidade, precisão e confiabilidade."',after:'"Esta funcionalidade é rápida, precisa e confiável."'},
  },
  'my-writing-style': {
    id:'my-writing-style', name:'My Writing Style', command:'/my-writing-style', plugin:'my-writing-style', catId:'escrever',
    tagline:'IA que aprende e replica seu estilo de escrita',
    desc:'Aprende seu estilo automaticamente a partir das suas edições. Quanto mais você corrige, mais próximo do seu tom fica.',
    stats:[{value:'auto',label:'aprendizado por edição'},{value:'0',label:'configuração manual'},{value:'∞',label:'melhora contínua'}],
    without:['Todo texto gerado soa como IA genérica','Tom inconsistente entre comunicações','Ajusta manualmente a voz em cada texto','Textos que parecem escritos por pessoas diferentes'],
    with:['Textos gerados com sua voz desde a primeira vez','Skill aprende com cada correção que você faz','Consistência de estilo em todos os canais','Menos edição manual a cada texto gerado'],
    example:{before:'SEM SKILL: "É com grande satisfação que compartilhamos nossa mais recente novidade..."',after:'COM /writing-style: "Lançamos uma feature nova.\nSem enrolação: aqui está o que mudou."'},
  },
  'playwright-skill': {
    id:'playwright-skill', name:'Playwright Skill', command:'/playwright-skill', plugin:'playwright-skill', catId:'browser',
    tagline:'Testes e2e completos com Playwright — detecção automática de dev server',
    desc:'Automação completa de browser. Auto-detecta servidores dev, testa páginas, valida UX e escreve scripts reutilizáveis.',
    stats:[{value:'auto',label:'detecção de dev server'},{value:'/tmp',label:'scripts salvos'},{value:'e2e',label:'cobertura de testes'}],
    without:['Testa manualmente — lento e não replicável','Bugs de UX descobertos em produção','Responsividade verificada na mão','Fluxos de login não testados sistematicamente'],
    with:['Fluxos completos testados automaticamente em segundos','Bugs de UX detectados antes do usuário ver','Responsividade verificada em múltiplas viewports','Scripts reutilizáveis para regressão futura'],
    example:{before:'// "Testei manualmente, parece que está funcionando!"',after:'✓ Detectado: localhost:3000\n✓ Login flow: 200ms\n✓ Dashboard carrega corretamente\n✓ Formulário valida campos obrigatórios\n✓ Mobile 375px: responsivo'},
  },
  'playwright-cli': {
    id:'playwright-cli', name:'Playwright CLI', command:'/playwright-cli', plugin:'playwright-skill', catId:'browser',
    tagline:'Comandos diretos de browser: open, goto, click, type',
    desc:'CLI de automação para interações específicas — navegar, clicar, digitar, screenshot — sem escrever código Playwright.',
    stats:[{value:'CDP',label:'Chrome DevTools Protocol'},{value:'6',label:'comandos principais'},{value:'0',label:'código para escrever'}],
    without:['Precisa escrever código Playwright para cada ação simples','Overhead de setup para automações rápidas','Difícil inspecionar elementos sem abrir DevTools','Automação one-shot que não vale um script'],
    with:['Acesso direto ao browser via comandos simples','Clica em elemento por ref do snapshot','Screenshot instantâneo sem código','Ideal para automações rápidas e exploração'],
    example:{before:'// Para verificar se o botão funciona preciso\n// escrever um script Playwright completo...',after:'playwright-cli open\nplaywright-cli goto https://app.meusite.com\nplaywright-cli click e15\nplaywright-cli screenshot'},
  },
  'playwright-trace': {
    id:'playwright-trace', name:'Playwright Trace', command:'/playwright-trace', plugin:'playwright-skill', catId:'browser',
    tagline:'Inspecionar traces de falhas de CI sem abrir browser',
    desc:'Inspeciona arquivos .zip de trace do Playwright via CLI — ações, requests, erros, snapshots. Funciona em ambientes sem GUI.',
    stats:[{value:'.zip',label:'formato de trace'},{value:'0',label:'browser necessário'},{value:'CI',label:'compatível com pipelines'}],
    without:['Abre trace no browser — bloqueado em ambientes sem GUI','Análise de falhas de CI requer download manual','Difícil identificar qual request causou timeout','Console e erros enterrados no trace visual'],
    with:['Inspeciona trace no terminal — funciona em CI','Lista ações com timestamps e localização no código','Filtra requests, console e erros em segundos','Snapshot DOM sem interface gráfica'],
    example:{before:'// CI falhou... preciso baixar o trace.zip\n// e abrir no browser para ver o que aconteceu',after:'$ npx playwright trace open trace.zip\n$ npx playwright trace errors\n→ TimeoutError em action#12: click #submit\n→ POST /api/login → 503'},
  },
  'agent-browser': {
    id:'agent-browser', name:'Agent Browser', command:'/agent-browser', plugin:'agent-browser', catId:'browser',
    tagline:'Automação de browser + Electron + Slack via Chrome CDP',
    desc:'CLI especializado para agentes IA com suporte a apps Electron, automação Slack e AWS Bedrock cloud browsers.',
    stats:[{value:'CDP',label:'Chrome DevTools Protocol'},{value:'4+',label:'tipos de automação'},{value:'cloud',label:'AWS Bedrock suportado'}],
    without:['Agente usa ferramentas web nativas — limitadas','Automação de apps Electron não suportada','Slack automation requer APIs complexas','Sem suporte a cloud browsers para escala'],
    with:['Controle total de Chrome via CDP','Automatiza VS Code, Slack, Discord, Figma, Spotify','Verificar unreads e enviar mensagens no Slack','Escala com AWS Bedrock AgentCore cloud browsers'],
    example:{before:'// Preciso verificar 20 canais do Slack para\n// ver quais têm mensagens não lidas...',after:'agent-browser skills get slack\n→ Verificando unreads em todos os canais...\n→ #engineering: 3 mensagens\n→ #deploys: 1 alerta crítico'},
  },
  'apify-ultimate-scraper': {
    id:'apify-ultimate-scraper', name:'Ultimate Scraper', command:'/apify-ultimate-scraper', plugin:'apify', catId:'dados',
    tagline:'Dados de 55+ plataformas selecionadas automaticamente',
    desc:'Scraper universal com IA que seleciona automaticamente o Actor certo para Instagram, TikTok, Google Maps e mais.',
    stats:[{value:'55+',label:'plataformas suportadas'},{value:'auto',label:'seleção de Actor'},{value:'JSON',label:'output estruturado'}],
    without:['Configura scraper diferente para cada plataforma','APIs bloqueadas ou com rate limit','Output não estruturado — parsear manualmente','Horas para dados que deveriam levar minutos'],
    with:['Um comando para qualquer plataforma','Dados estruturados prontos para análise','Google Maps, Instagram, TikTok sem APIs pagas','Lead gen e análise de concorrentes em minutos'],
    example:{before:'// Preciso dos reviews do concorrente no Google Maps\n// Vou ter que fazer scraping manual...',after:'/apify-ultimate-scraper\n→ "reviews Restaurante XYZ no Google Maps"\n→ Actor: google-maps-reviews selecionado\n→ 247 reviews exportados em JSON ✓'},
  },
  'apify-actor-development': {
    id:'apify-actor-development', name:'Actor Development', command:'/apify-actor-development', plugin:'apify', catId:'dados',
    tagline:'Actors serverless Docker para scraping na nuvem',
    desc:'Desenvolve, debuga e faz deploy de Apify Actors — programas serverless que rodam na nuvem e escalam automaticamente.',
    stats:[{value:'Docker',label:'ambiente isolado'},{value:'serverless',label:'escala automática'},{value:'apify push',label:'deploy em 1 comando'}],
    without:['Scraper que quebra a cada mudança de layout','Infraestrutura local para gerenciar','Sem persistência de estado entre execuções','Escala manual conforme demanda cresce'],
    with:['Actor Docker isolado e resiliente','Escala automática na infraestrutura Apify','Estado persistido — retoma de onde parou','Deploy com apify push — sem DevOps'],
    example:{before:'// Rodando scraper local que quebra se o IP bane...',after:'$ apify run --input \'{"url":"..."}\'\n// Testado localmente\n$ apify push\n// Rodando na nuvem, escalável ✓'},
  },
  'apify-actorization': {
    id:'apify-actorization', name:'Actorization', command:'/apify-actorization', plugin:'apify', catId:'dados',
    tagline:'Converter qualquer projeto em Actor serverless Apify',
    desc:'Transforma código existente (JS/TS, Python, qualquer linguagem) em Apify Actors prontos para deploy.',
    stats:[{value:'3',label:'linguagens suportadas'},{value:'5',label:'passos de migração'},{value:'reutilizável',label:'resultado final'}],
    without:['Script local que só roda na sua máquina','Sem input schema — configuração hardcoded','Impossível compartilhar o script','Sem monitoramento de execuções'],
    with:['Projeto convertido em Actor na nuvem','Input schema JSON para configuração','Compartilhável no Apify Store','Histórico de execuções e logs'],
    example:{before:'// script.py — roda só no meu notebook\n// "Alguém pode usar?"\n// "Não, só eu tenho o ambiente configurado"',after:'$ apify init && apify push\n// Actor disponível na nuvem\n// Qualquer um pode usar com input JSON ✓'},
  },
  'apify-generate-output-schema': {
    id:'apify-generate-output-schema', name:'Output Schema', command:'/apify-generate-output-schema', plugin:'apify', catId:'dados',
    tagline:'Schema de output gerado do código — nunca adivinhado',
    desc:'Analisa o código fonte do Actor para gerar schemas precisos: dataset_schema.json, output_schema.json e key_value_store_schema.json.',
    stats:[{value:'3',label:'schemas gerados'},{value:'100%',label:'campos nullable'},{value:'0',label:'suposições no schema'}],
    without:['Schema escrito manualmente — difícil de manter','Campos non-nullable que quebram quando API muda','Console Apify não exibe os dados corretamente','Exemplos com dados reais de usuários (privacidade)'],
    with:['Schema gerado do código — sempre em sincronia','Todos os campos nullable — resistente a mudanças','Console exibe os dados corretamente','Exemplos anonimizados — zero dados reais'],
    example:{before:'// dataset_schema.json escrito na mão\n// "Acho que o campo email é string..."\n// (na verdade pode ser null)',after:'// Analisando código do Actor...\n// email: sempre nullable=true ✓\n// dataset_schema.json gerado com 12 campos ✓'},
  },
  caveman: {
    id:'caveman', name:'Caveman Mode', command:'/caveman', plugin:'caveman', catId:'produtividade',
    tagline:'Reduz tokens ~75% — mantém precisão técnica total',
    desc:'Modo ultra-comprimido. Elimina artigos, cortesias e filler. Substância técnica permanece 100% intacta.',
    stats:[{value:'-75%',label:'tokens por resposta'},{value:'3',label:'níveis: lite/full/ultra'},{value:'100%',label:'precisão técnica'}],
    without:['"Claro! Fico feliz em ajudar com isso..."','Resposta de 300 palavras para problema de 3 linhas','Resumos do que acabou de fazer no final','Tokens desperdiçados em cortesia e preâmbulo'],
    with:['Vai direto ao ponto — zero preâmbulo','Resposta de 30 palavras para problema de 3 linhas','Código inalterado — só prosa comprimida','Ativo até "stop caveman" — consistente'],
    example:{before:'"Excelente pergunta! Para resolver este problema, precisamos primeiro entender o contexto e então analisar as opções disponíveis..."',after:'"Bug: auth middleware usa `<` não `<=`. Fix:"'},
  },
  'cost-mode': {
    id:'cost-mode', name:'Cost Mode', command:'/cost-mode', plugin:'cost-mode', catId:'produtividade',
    tagline:'Reduz custos 30–60% sem sacrificar precisão técnica',
    desc:'Modo econômico estruturado. Remove tudo que não é substância: cortesias, hedging, repetição do prompt.',
    stats:[{value:'-60%',label:'custo por sessão'},{value:'-70%',label:'tokens de output'},{value:'3',label:'níveis de intensidade'}],
    without:['Agente repete o prompt antes de responder','Resumo do "que acabei de fazer" em todo turno','"Certamente! Vou ajudá-lo com isso..."','Custo mensal alto por tokens desnecessários'],
    with:['Resposta começa direto com a substância','Sem trailing summaries','Sem hedging desnecessário','Custo mensal significativamente reduzido'],
    example:{before:'"Claro! Você me pediu para refatorar a função de auth. Vou fazer isso agora. Aqui está o resultado: [...] Espero que isso ajude!"',after:'```ts\nconst auth = (token: string) => { ... }\n```'},
  },
  'mem-search': {
    id:'mem-search', name:'Mem Search', command:'/mem-search', plugin:'thedotmack', catId:'produtividade',
    tagline:'Buscar trabalho de sessões anteriores via claude-mem',
    desc:'Acessa memória persistente entre sessões com busca semântica por projeto, data, conceito ou tipo de observação.',
    stats:[{value:'3',label:'camadas de busca'},{value:'-10×',label:'tokens vs busca direta'},{value:'∞',label:'sessões acessíveis'}],
    without:['Começa do zero em toda nova sessão','Re-explica o mesmo contexto repetidamente','Bug já resolvido resolvido novamente','Sem memória de decisões e trade-offs'],
    with:['Busca trabalho passado por projeto, data ou conceito','Recupera como um problema foi resolvido','Reutiliza soluções sem refazer a investigação','Continuidade real entre sessões'],
    example:{before:'// "Como a gente fez o deploy do flowcrm mesmo?\n// Vou ter que perguntar de novo..."',after:'search("flowcrm deploy")\n→ 2026-04-15: Easypanel + git push\n→ Branch main → deploy automático ✓'},
  },
  'knowledge-agent': {
    id:'knowledge-agent', name:'Knowledge Agent', command:'/knowledge-agent', plugin:'thedotmack', catId:'produtividade',
    tagline:'Bases de conhecimento IA consultáveis por tema',
    desc:'Compila corpus filtrado de observações passadas em um "cérebro" especializado — consultável conversacionalmente.',
    stats:[{value:'corpus',label:'filtrado por tema'},{value:'conversa',label:'interface de consulta'},{value:'∞',label:'observações indexáveis'}],
    without:['Expertise acumulada existe só na cabeça do dev','Busca no histórico de sessões — muito ruído','Conhecimento espalhado em milhares de linhas','Precisa re-aprender o contexto a cada tarefa'],
    with:['"Cérebro" focado: "tudo sobre hooks", "todos os bugfixes do worker"','Consulta conversacional com contexto especializado','Filtra por tipo, conceito, arquivo ou período','Expertise do projeto disponível instantaneamente'],
    example:{before:'// "Como funciona o sistema de hooks do claude-mem?"\n// Vou ter que ler o código todo do zero...',after:'build_corpus "hooks-expertise" concept="hooks"\n// 47 observações relevantes carregadas\n"Como funciona o lifecycle dos hooks?"\n→ Resposta contextualizada ✓'},
  },
  'timeline-report': {
    id:'timeline-report', name:'Timeline Report', command:'/timeline-report', plugin:'thedotmack', catId:'produtividade',
    tagline:'Narrativa completa da história de desenvolvimento',
    desc:'Gera relatório "Journey Into [Projeto]" analisando todo o histórico via claude-mem — decisões, bugs, features, refatorações.',
    stats:[{value:'100%',label:'histórico coberto'},{value:'1',label:'relatório narrativo'},{value:'timeline',label:'formato de análise'}],
    without:['História do projeto vive só no git log sem contexto','Difícil onboarding de novos devs','Decisões arquiteturais esquecidas com o tempo','Padrões de bugs recorrentes não identificados'],
    with:['Narrativa completa com decisões e motivações','Contexto de onboarding em um relatório','Padrões de bugs identificados ao longo do tempo','História do projeto preservada e consultável'],
    example:{before:'// "Por que fizemos assim mesmo?"\n// "Acho que tinha um motivo, mas não lembro..."',after:'## Journey Into FlowCRM\n### Semana 1: Auth System\nDecidimos JWT sobre sessions por motivo X...\n### Semana 3: Bug crítico em billing corrigido...'},
  },
  'find-skills': {
    id:'find-skills', name:'Find Skills', command:'/find-skills', plugin:'find-skills', catId:'produtividade',
    tagline:'Descobrir e instalar skills do marketplace skills.sh',
    desc:'Busca skills por funcionalidade, verifica qualidade (installs, reputação, stars) e sugere comando de instalação.',
    stats:[{value:'skills.sh',label:'marketplace'},{value:'1k+',label:'installs mínimos recomendados'},{value:'npx',label:'instalação direta'}],
    without:['Não sabe que existe skill para a tarefa','Reinventa a roda — implementa algo que já existe como skill','Instala skill de baixa qualidade sem verificar','Claude Code com capacidades subutilizadas'],
    with:['Descobre skills antes de implementar do zero','Verifica installs, fonte e stars no GitHub','Instala com npx skills add ...','Claude Code com capacidades sempre expandidas'],
    example:{before:'"Preciso automatizar o browser..."\n// Vai implementar manualmente com Puppeteer...',after:'/find-skills automação browser\n→ agent-browser (185k installs, Vercel Labs)\nnpx skills add agent-browser@agent-browser -g -y'},
  },
  'context7-cli': {
    id:'context7-cli', name:'Context7 CLI', command:'/context7-cli', plugin:'context7-cli', catId:'produtividade',
    tagline:'Documentação atualizada de qualquer lib em tempo real',
    desc:'Busca docs atualizados para qualquer biblioteca — o training data pode estar desatualizado. Também gerencia skills.',
    stats:[{value:'live',label:'docs em tempo real'},{value:'0',label:'APIs inventadas'},{value:'MCP',label:'configuração integrada'}],
    without:['Usa API do training data que foi removida na versão atual','Exemplos de código desatualizados que não compilam','Debugging de "por que essa função não existe?"','Tempo perdido com APIs deprecated'],
    with:['Docs atualizados da versão que você está usando','APIs verificadas antes de usar','Exemplos de código que realmente funcionam','MCP configurado para acesso contínuo'],
    example:{before:'// useFormStatus() do React — existe mesmo?\n// O Claude "acha" que existe mas talvez seja\n// de uma versão diferente...',after:'$ npx ctx7 get react-dom\n→ useFormStatus: disponível desde React 19 ✓\n→ Import: from "react-dom" (não "react") ✓'},
  },
  'using-superpowers': {
    id:'using-superpowers', name:'Using Superpowers', command:'/using-superpowers', plugin:'superpowers', catId:'produtividade',
    tagline:'Skill mestre — como encontrar e usar todas as skills',
    desc:'Estabelece o comportamento fundamental: invocar skill relevante ANTES de qualquer resposta. Define prioridades e red flags.',
    stats:[{value:'1%',label:'chance = obrigado a checar'},{value:'0',label:'respostas antes de checar'},{value:'∞',label:'skills acessíveis'}],
    without:['Claude responde sem checar se existe skill melhor','Skills instaladas mas nunca invocadas','Racionaliza "esse caso é simples, não precisa de skill"','Investimento em skills que não são usadas'],
    with:['Checa skills antes de qualquer resposta — sempre','Skills relevantes invocadas automaticamente','Sem racionalização — se há 1% de chance, checa','Retorno máximo das skills instaladas'],
    example:{before:'// Usuário: "tem um bug aqui"\n// Claude: "Parece simples, vou corrigir direto"\n// (sem usar systematic-debugging)',after:'// Usuário: "tem um bug aqui"\n// Claude: invoca /systematic-debugging\n// → causa raiz encontrada antes de qualquer fix ✓'},
  },
};
